beclab/apps

duplicati/Chart.yaml, duplicati/TerminusManifest.yaml
Duplicati 
Upload the icon to CDN, and change icon url inTerminusManifest.yaml accordingly
=> [UPDATE][duplicati][0.0.2]change icon url

r4techbiz/Chart.yaml, r4techbiz/TerminusManifest.yaml
=> [UPDATE][r4techbiz][0.1.21]update featured image

r4sport/Chart.yaml, r4sport/TerminusManifest.yaml
=> [UPDATE][r4sport][0.1.24]Update Featured Image

r4tech/Chart.yaml, r4tech/TerminusManifest.yaml
=> [UPDATE][r4tech][0.0.11]Update Featured Image

r4business/Chart.yaml, r4business/TerminusManifest.yaml
=> [UPDATE][r4business][0.1.23]Update Featured Image

r4world/Chart.yaml, r4world/TerminusManifest.yaml
=> [UPDATE][r4world][0.1.28]Change Featured Image

r4entertainment/Chart.yaml, r4entertainment/TerminusManifest.yaml
Entertainment
Change to a new cover image
=> [UPDATE][r4entertainment][0.1.25]Change Featured Image

stealth7b/Chart.yaml, stealth7b/TerminusManifest.yaml
=> [UPDATE][stealth7b][0.0.3]Fix featuredImage

noromaid7b/Chart.yaml, noromaid7b/TerminusManifest.yaml
=> [UPDATE][noromaid7b][0.0.3]noromaid7b

codeninja7bq4/Chart.yaml, codeninja7bq4/TerminusManifest.yaml
=> [UPDATE][codeninja7bq4][0.0.4]Fix Cover

phi23b/Chart.yaml, phi23b/TerminusManifest.yaml
=> [UPDATE][phi23b][0.0.5]update featured image

mistralins7bq4/Chart.yaml, mistralins7bq4/TerminusManifest.yaml
Mistral Instruct 7B
Switch to a new Featured Image
=> [UPDATE][mistralins7bq4][0.0.3]change featured image

llama2chat7bq4/Chart.yaml, llama2chat7bq4/TerminusManifest.yaml
=> [UPDATE][llama2chat7bq4][0.0.4]Update Featured Image

yarnmistral7b/Chart.yaml, yarnmistral7b/TerminusManifest.yaml
=> [UPDATE][yarnmistral7b][0.0.3]Change Featured Image

openchat7b/Chart.yaml, openchat7b/TerminusManifest.yaml
=> [UPDATE][openchat7b][0.0.3]fix featured image

README.md
Update readme title and links, modify repo description a little bit
=> [Doc]Update repository README

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml
SD Web UI
Reduce required GPU memory to 4Gi.
=> [UPDATE][sdwebui][0.0.4]Reduce required GPU

onlyoffice/Chart.yaml, onlyoffice/TerminusManifest.yaml
OnlyOffice
fix entrance and update os dependencies
=> [UPDATE][onlyoffice][0.0.6]fix entrance and update os dependencies

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml, sdwebui/templates/deployment.yaml
SD Web UI
Reduce required memory to 3Gi.
=> [UPDATE][sdwebui][0.0.5]reduce requiredMemory

nostream/Chart.yaml, nostream/TerminusManifest.yaml, nostream/templates/deployment.yaml
nostream
> change db to system db
>
> config entrance authLevel
=> [UPDATE][nostream][0.0.5]change db to system db

onlyoffice/Chart.yaml, onlyoffice/TerminusManifest.yaml, onlyoffice/templates/deployment.yaml
onlyoffice
Reduce required CPU
=> [UPDATE][onlyoffice][0.0.7]Reduce required CPU

mastodon/Chart.yaml, mastodon/TerminusManifest.yaml, mastodon/templates/all.yaml
Mastodon
Reduce CPU and Memory requirement
=> [UPDATE][mastodon][0.0.6]reduce required cpu and memory

bytebase/Chart.yaml, bytebase/TerminusManifest.yaml, bytebase/templates/proxy.yaml
=>  [UPDATE][bytebase][0.0.7]reduce required cpu

jellyfin/Chart.yaml, jellyfin/TerminusManifest.yaml, jellyfin/templates/deployment.yaml
=> [UPDATE][jellyfin][0.0.4]reduce cpu

affine/Chart.yaml, affine/TerminusManifest.yaml, affine/templates/deployment.yaml
affine
Reduce requiredCpu to 0.25
=> [UPDATE][affine][0.0.5]reduce cpu

n8n/Chart.yaml, n8n/TerminusManifest.yaml, n8n/templates/n8n.yaml
=> [UPDATE][n8n][0.0.7]reduce cpu & memory

r4business/Chart.yaml, r4business/TerminusManifest.yaml, r4business/templates/prerank.yaml, r4business/templates/rank.yaml
=> [UPDATE][r4business][0.1.24]

r4entertainment/Chart.yaml, r4entertainment/TerminusManifest.yaml, r4entertainment/templates/prerank.yaml, r4entertainment/templates/rank.yaml
=> [UPDATE][r4entertainment][0.1.26]

r4sport/Chart.yaml, r4sport/TerminusManifest.yaml, r4sport/templates/prerank.yaml, r4sport/templates/rank.yaml
=> [UPDATE][r4sport][0.1.25]

r4tech/Chart.yaml, r4tech/TerminusManifest.yaml, r4tech/templates/prerank.yaml, r4tech/templates/rank.yaml
=> [UPDATE][r4tech][0.0.13]

r4techbiz/Chart.yaml, r4techbiz/TerminusManifest.yaml, r4techbiz/templates/prerank.yaml, r4techbiz/templates/rank.yaml
=> [UPDATE][r4techbiz][0.1.22]

r4world/Chart.yaml, r4world/TerminusManifest.yaml, r4world/templates/prerank.yaml, r4world/templates/rank.yaml
=> [UPDATE][r4world][0.1.29]

qbittorrent/Chart.yaml, qbittorrent/TerminusManifest.yaml, qbittorrent/templates/deployment.yaml, qbittorrent/templates/services.yaml
> qbittorrent
> disable login & update io config
=> [UPDATE][qbittorrent][0.0.5]disable login & update io config

qbittorrent/Chart.yaml, qbittorrent/TerminusManifest.yaml, qbittorrent/templates/deployment.yaml
> qbittorrent
> save config & download progress
=> [UPDATE][qbittorrent][0.0.8]save config & download progress

showdoc/Chart.yaml, showdoc/TerminusManifest.yaml, showdoc/templates/showdoc.yaml
> showdoc
> add readinessProbe
=> [UPDATE][showdoc][0.0.5]add readinessProbe

codeserver/Chart.yaml, codeserver/TerminusManifest.yaml, codeserver/templates/codeserver.yaml
=> [UPDATE][codeserver][0.0.11]disable login

nocodb/Chart.yaml, nocodb/TerminusManifest.yaml, nocodb/templates/deployment.yaml
> nocodb
> update entrances config & change db to system db
=> [UPDATE][nocodb][0.0.8]update entrances config & change db to system db

nextcloud/Chart.yaml, nextcloud/TerminusManifest.yaml, nextcloud/templates/deployment.yaml
> nextcloud
> change db to system db
=> [UPDATE][nextcloud][0.0.12]change db to system db

sonarr/Chart.yaml, sonarr/TerminusManifest.yaml, sonarr/templates/deployment.yaml
> sonarr
> fix limit & update data config
=> [UPDATE][sonarr][0.0.6]fix limit & update data config

radarr/Chart.yaml, radarr/TerminusManifest.yaml, radarr/templates/deployment.yaml
=> [UPDATE][radarr][0.0.6]fix install

transmission/Chart.yaml, transmission/TerminusManifest.yaml, transmission/templates/deployment.yaml
> transmission
> change downloads path to user home
=> [UPDATE][transmission][0.0.3]change downloads path to user home

farcasterhubble/Chart.yaml, farcasterhubble/TerminusManifest.yaml, farcasterhubble/owners, farcasterhubble/templates/deployment.yaml
> farcasterhubble
> new app farcasterhubble
=> [NEW][farcasterhubble][0.0.23]new app farcasterhubble

wordpress/Chart.yaml, wordpress/TerminusManifest.yaml, wordpress/templates/proxy.yaml
WordPress
update image repo, improve initial robustness
=> [UPDATE][wordpress][0.0.13]update image repo, improve initial robustness

wordpress/Chart.yaml, wordpress/TerminusManifest.yaml
=> [UPDATE][wordpress][0.0.14]add promoteImage

novella/Chart.yaml, novella/TerminusManifest.yaml, novella/templates/deployment.yaml
=> [UPDATE][novella][0.0.12]update domain

gitlabpure/Chart.yaml, gitlabpure/TerminusManifest.yaml
> gitlabpure
> update openMethod
=> [UPDATE][gitlabpure][0.0.48]update openMethod

penpot/.helmignore, penpot/Chart.yaml, penpot/TerminusManifest.yaml, penpot/owners, penpot/templates/_helpers.tpl, penpot/templates/backend/deployment.yaml, penpot/templates/backend/service.yaml, penpot/templates/exporter/deployment.yaml, penpot/templates/exporter/service.yaml, penpot/templates/frontend/deployment.yaml, penpot/templates/frontend/service.yaml, penpot/templates/redis/deployment.yaml, penpot/templates/redis/service.yaml, penpot/values.yaml
> penpot
> Penpot is the web-based open-source design tool that bridges
the gap between designers and developers.
=> [NEW][penpot][0.0.1]add penpot

comfyui/Chart.yaml, comfyui/TerminusManifest.yaml
=> [UPDATE][comfyui][0.0.15]add promoteImage

ghost/Chart.yaml, ghost/TerminusManifest.yaml, ghost/templates/deployment.yaml
ghost
add image and adjust resources
=> [UPDATE][ghost][0.0.5]add image and adjust resources

farcasterhubble/Chart.yaml, farcasterhubble/TerminusManifest.yaml
Hubble
update description and add promotion images
=> [UPDATE][farcasterhubble][0.0.24]update description and add promotion images

gitlabfusion/Chart.yaml, gitlabfusion/TerminusManifest.yaml, gitlabfusion/templates/clientproxy.yaml, gitlabfusion/templates/serverproxy.yaml
> gitlabfusion
> fix domain in web & fix auto login multi user
=> [UPDATE][gitlabfusion][0.0.99]fix domain in web & fix auto login multi user

gitlabfusionclient/Chart.yaml, gitlabfusionclient/TerminusManifest.yaml, gitlabfusionclient/templates/clientproxy.yaml
> gitlabfusionclient
> fix domain in web & fix auto login multi user
=> [UPDATE][gitlabfusionclient][0.0.26]fix domain in web & fix auto login multi user

sickchill/Chart.yaml, sickchill/TerminusManifest.yaml, sickchill/templates/deployment.yaml
> sickchill
> Configure user directory
=> [UPDATE][sickchill][0.0.3]Configure user directory

deluge/Chart.yaml, deluge/TerminusManifest.yaml, deluge/templates/deployment.yaml
> deluge
> update config user directory
=> [UPDATE][deluge][0.0.3]update config user directory

codeserver/Chart.yaml, codeserver/TerminusManifest.yaml, codeserver/templates/chartmuseum.yaml, codeserver/templates/codeserver.yaml
codeserver
delete default credentials
=> [UPDATE][codeserver][0.0.13]delete default credentials

chinesesubfinder/Chart.yaml, chinesesubfinder/TerminusManifest.yaml, chinesesubfinder/templates/chinesesubfinder.yaml
> chinesesubfinder
> update config user directory
=> [UPDATE][chinesesubfinder][0.0.2]update config user directory

nzbget/Chart.yaml, nzbget/TerminusManifest.yaml, nzbget/templates/deployment.yaml
> nzbget
> update config user directory
=> [UPDATE][nzbget][0.0.7]update config user directory

duplicati/Chart.yaml, duplicati/TerminusManifest.yaml, duplicati/templates/deployment.yaml
> duplicati
> update config user directory
=> [UPDATE][duplicati][0.0.3]update config user directory

ghost/Chart.yaml, ghost/TerminusManifest.yaml
> ghost
> update entrances config
=> [UPDATE][ghost][0.0.7]update entrances config

obsidian/Chart.yaml, obsidian/TerminusManifest.yaml, obsidian/templates/deployment.yaml
> obsidian
> 30x to /_utils & update config entrances
=> [UPDATE][obsidian][0.0.11]30x to /_utils & update config entrances

obsidian/Chart.yaml, obsidian/TerminusManifest.yaml
> obsidian
> change entrance to private
=> [UPDATE][obsidian][0.0.12]change entrance to private

navidrome/Chart.yaml, navidrome/TerminusManifest.yaml, navidrome/templates/deployment.yaml
> navidrome
> update default path
=> [UPDATE][navidrome][0.0.6]update default path

ipfs/Chart.yaml, ipfs/TerminusManifest.yaml, ipfs/templates/deployment.yaml
> ipfs
> Update config directory & Add initialization process
=> [UPDATE][ipfs][0.0.20]Update config directory & Add initialization process

ipfs/Chart.yaml, ipfs/TerminusManifest.yaml, ipfs/templates/deployment.yaml
=> [UPDATE][ipfs][0.0.28]support local

ipfs/Chart.yaml, ipfs/TerminusManifest.yaml, ipfs/templates/deployment.yaml
> ipfs
> update config client_max_body_size
=> [UPDATE][ipfs][0.0.29]update config client_max_body_size

codeserver/Chart.yaml, codeserver/TerminusManifest.yaml, codeserver/templates/codeserver.yaml
=> [UPDATE][codeserver][0.0.14]fix init shell

penpot/Chart.yaml, penpot/TerminusManifest.yaml, penpot/templates/backend/deployment.yaml, penpot/templates/exporter/deployment.yaml, penpot/templates/frontend/deployment.yaml
> penpot
> update penpot to 0.0.3 fix public url
=> [UPDATE][penpot][0.0.3]update penpot

r4business/Chart.yaml, r4business/TerminusManifest.yaml, r4business/templates/embedding.yaml, r4business/templates/prerank.yaml, r4business/templates/rank.yaml, r4business/templates/train.yaml
=> [UPDATE][r4business][0.1.25]update extractor

mongodb/.helmignore, mongodb/Chart.yaml, mongodb/TerminusManifest.yaml, mongodb/owners, mongodb/templates/_helpers.tpl, mongodb/templates/deployment.yaml, mongodb/values.yaml
MongoDB 6.0
Add the mongoDB Middleware
=> [NEW][mongodb][6.0.4]feat: add middleware mongodb

otmoiclp/Chart.yaml, otmoiclp/TerminusManifest.yaml
Otmoic LP
add mongodb denpendency
=> [UPDATE][otmoiclp][0.0.18]feat: add mongodb denpendency

calendar/.helmignore, calendar/Chart.yaml, calendar/TerminusManifest.yaml, calendar/owners, calendar/templates/_helpers.tpl, calendar/templates/calendar_deploy.yaml, calendar/values.yaml
Calendar
submit app "Calendar"
=> [NEW][calendar][0.0.1] add calendar

mattermost/Chart.yaml, mattermost/TerminusManifest.yaml, mattermost/owners, mattermost/templates/configmap.yaml, mattermost/templates/mattermost.yaml, mattermost/templates/secret.yaml
> Mattermost
> new app mattermost
=> [NEW][mattermost][0.0.6]new app mattermost

devbox/Chart.yaml, devbox/TerminusManifest.yaml, devbox/templates/deployment.yaml
DevBox
update provider api to v2
=> [UPDATE][devbox][0.0.4]update provider api

difyfusion/.helmignore, difyfusion/Chart.yaml, difyfusion/TerminusManifest.yaml, difyfusion/owners, difyfusion/templates/_helpers.tpl, difyfusion/templates/deployment.yaml, difyfusion/values.yaml
=> [NEW][difyfusion][0.0.1]add dify funsion

difyfusionclient/.helmignore, difyfusionclient/Chart.yaml, difyfusionclient/TerminusManifest.yaml, difyfusionclient/owners, difyfusionclient/templates/_helpers.tpl, difyfusionclient/templates/dify_fe_deploy.yaml, difyfusionclient/values.yaml
=> [NEW][difyfusionclient][0.0.1]add difyfusionclient

obsidian/Chart.yaml, obsidian/README.md, obsidian/TerminusManifest.yaml, obsidian/owners
=> [UPDATE][obsidian][0.0.14]update icon and description

nostream/Chart.yaml, nostream/TerminusManifest.yaml, nostream/owners
=> [UPDATE][nostream][0.0.6]update icon and description

gitlabpure/Chart.yaml, gitlabpure/TerminusManifest.yaml, gitlabpure/owners
=> [UPDATE][gitlabpure][0.0.49]update icon and description

gitlabfusion/Chart.yaml, gitlabfusion/TerminusManifest.yaml, gitlabfusion/owners
=> [UPDATE][gitlabfusion][0.0.100]update icon and description

comfyui/Chart.yaml, comfyui/TerminusManifest.yaml, comfyui/owners
=>  [UPDATE][comfyui][0.0.16]update icon and description

nocodb/Chart.yaml, nocodb/TerminusManifest.yaml, nocodb/owners
=> [UPDATE][nocodb][0.0.9]update icon and description

difyfusionclient/Chart.yaml, difyfusionclient/TerminusManifest.yaml, difyfusionclient/templates/dify_fe_deploy.yaml
Dify Gateway
update ProviderRegistry
=> [UPDATE][difyfusionclient][0.0.2]update ProviderRegistry

bazarr/Chart.yaml, bazarr/TerminusManifest.yaml, bazarr/templates/deployment.yaml
=> [UPDATE][bazarr][0.0.6] add legacy provider

readarr/Chart.yaml, readarr/TerminusManifest.yaml, readarr/templates/deployment.yaml
=> [UPDATE][readarr][0.0.5]add legacy provider

prowlarr/Chart.yaml, prowlarr/TerminusManifest.yaml, prowlarr/templates/deployment.yaml
=> [UPDATE][prowlarr][0.0.10]add legacy provider

sonarr/Chart.yaml, sonarr/TerminusManifest.yaml, sonarr/templates/deployment.yaml
=>  [UPDATE][sonarr][0.0.11]add legacy provider

nzbget/Chart.yaml, nzbget/TerminusManifest.yaml, nzbget/templates/deployment.yaml
=> [UPDATE][nzbget][0.0.8]add legacy provider

deluge/Chart.yaml, deluge/TerminusManifest.yaml, deluge/templates/deployment.yaml
=> [UPDATE][deluge][0.0.4]add legacy provider

transmission/Chart.yaml, transmission/TerminusManifest.yaml, transmission/templates/deployment.yaml
transmission
add legacy provider
=> [UPDATE][transmission][0.0.4]add legacy provider

radarr/Chart.yaml, radarr/README.md, radarr/TerminusManifest.yaml
radarr
fix config in permission and cpu arch
fix description format
add readme file for config download client
=> [UPDATE][radarr][0.0.8]bug fix and add config guide readme

perplexica/Chart.yaml, perplexica/TerminusManifest.yaml, perplexica/owners, perplexica/templates/backend.yaml, perplexica/templates/frontend.yaml
> perplexica
> new app perplexica
=> [NEW][perplexica][0.0.11]new app perplexica

ollama/Chart.yaml, ollama/TerminusManifest.yaml, ollama/owners, ollama/templates/deployment.yaml
=> [NEW][ollama][0.0.6]new app ollama

searxng/Chart.yaml, searxng/TerminusManifest.yaml, searxng/owners, searxng/templates/deployment.yaml
=> [NEW][searxng][0.0.13]new app searxng

searxng/Chart.yaml, searxng/TerminusManifest.yaml
=> [UPDATE][searxng][0.0.14]fix title

ollama/Chart.yaml, ollama/TerminusManifest.yaml, ollama/templates/openwebui.yaml
> Olllama
> Embed OpenWebui into Olllama
=> [UPDATE][ollama][0.0.12]Embed OpenWebui into Olllama

radarr/Chart.yaml, radarr/README.md, radarr/TerminusManifest.yaml
=> [UPDATE][radarr][0.0.9]fix readme format bug

mongodb/Chart.yaml, mongodb/TerminusManifest.yaml, mongodb/templates/deployment.yaml
mongodb
fix install error on arm64
=> [UPDATE][mongodb][6.0.5]fix install error on arm64

jellyfin/Chart.yaml, jellyfin/TerminusManifest.yaml, jellyfin/templates/deployment.yaml
> jellyfin
> Fix the issue of configuration loss upon restart.
=> [UPDATE][jellyfin][0.0.11]Fix the issue of configuration loss upon restart.

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml, openwebui/owners, openwebui/templates/deployment.yaml
> openwebui
> new app openwebui
=> [NEW][openwebui][0.0.6]new app openwebui

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml, openwebui/templates/deployment.yaml
> openwebui
> add config: gaianetai api
=> [UPDATE][openwebui][0.0.8]add config: gaianetai api

gaianetai/.helmignore, gaianetai/Chart.yaml, gaianetai/TerminusManifest.yaml, gaianetai/owners, gaianetai/templates/deployment.yaml
> gaianetai
> new app gaianetai
=> [NEW][gaianetai][0.0.5]new app gaianetai

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml
> openwebui
> add support app : whisper
=> [UPDATE][openwebui][0.0.9]add support app : whisper

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml
=> [UPDATE][openwebui][0.0.10]support app: openedai-speech

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml
> openwebui
> support new api: sdwebui
=> [UPDATE][openwebui][0.0.12]support new api: sdwebui

r4business/Chart.yaml, r4business/TerminusManifest.yaml, r4business/templates/embedding.yaml, r4business/templates/rank.yaml, r4business/templates/train.yaml
r4business
add recommend reason
=> [UPDATE][r4business][0.1.36]add recommend reason

r4sport/Chart.yaml, r4sport/TerminusManifest.yaml, r4sport/templates/prerank.yaml, r4sport/templates/rank.yaml, r4sport/templates/train.yaml
=> [UPDATE][r4sport][0.1.36]add recommend reason

openedaispeech/Chart.yaml, openedaispeech/TerminusManifest.yaml, openedaispeech/owners, openedaispeech/templates/deployment.yaml
> openedaispeech
> new app openedai-speech
=> [NEW][openedaispeech][0.0.7]new app openedai-speech

whisper/Chart.yaml, whisper/TerminusManifest.yaml, whisper/owners, whisper/templates/deployment.yaml
=> [NEW][whisper][0.0.6]new app whisper

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml
=> [UPDATE][openwebui][0.0.13]fix svc config

otmoiclp/Chart.yaml, otmoiclp/TerminusManifest.yaml, otmoiclp/owners, otmoiclp/templates/admin.yaml, otmoiclp/templates/amm.yaml, otmoiclp/templates/amm_analytics.yaml, otmoiclp/templates/analyse.yaml, otmoiclp/templates/dashboard.yaml, otmoiclp/templates/evm_bsc.yaml, otmoiclp/templates/graphql.yaml, otmoiclp/templates/lpnode.yaml, otmoiclp/templates/market.yaml, otmoiclp/templates/solana_solana.yaml, otmoiclp/templates/traefik.yaml
=> [UPDATE][otmoiclp][0.0.19]support solana

affine/Chart.yaml, affine/TerminusManifest.yaml, affine/templates/deployment.yaml
=> [UPDATE][affine][0.0.9]lock image

astral/Chart.yaml, astral/TerminusManifest.yaml, astral/templates/deployment.yaml
=> [UPDATE][astral][0.0.4]lock image

bazarr/Chart.yaml, bazarr/TerminusManifest.yaml, bazarr/templates/deployment.yaml
=> [UPDATE][bazarr][0.0.7]lock image

bytebase/Chart.yaml, bytebase/TerminusManifest.yaml, bytebase/templates/bytebase.yaml, bytebase/templates/proxy.yaml
=> [UPDATE][bytebase][0.0.12]lock image

calendar/Chart.yaml, calendar/TerminusManifest.yaml, calendar/templates/calendar_deploy.yaml
=> [UPDATE][calendar][0.0.2]lock image

calibre/Chart.yaml, calibre/TerminusManifest.yaml, calibre/templates/deployment.yaml
=> [UPDATE][calibre][0.0.2]lock image

calibreweb/Chart.yaml, calibreweb/TerminusManifest.yaml, calibreweb/templates/deployment.yaml
=> [UPDATE][calibreweb][0.0.3]lock image

chinesesubfinder/Chart.yaml, chinesesubfinder/TerminusManifest.yaml, chinesesubfinder/templates/chinesesubfinder.yaml
> chinesesubfinder
> lock image
=> [UPDATE][chinesesubfinder][0.0.3]lock image

chromium/Chart.yaml, chromium/TerminusManifest.yaml, chromium/templates/chromium.yaml
=> [UPDATE][chromium][0.0.2]lock image

codeserver/Chart.yaml, codeserver/TerminusManifest.yaml, codeserver/templates/chartmuseum.yaml, codeserver/templates/codeserver.yaml
=> [UPDATE][codeserver][0.0.15]lock image

comfyui/Chart.yaml, comfyui/TerminusManifest.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][0.0.17]lock image

deluge/Chart.yaml, deluge/TerminusManifest.yaml, deluge/templates/deployment.yaml
=> [UPDATE][deluge][0.0.6]lock image

devbox/Chart.yaml, devbox/TerminusManifest.yaml, devbox/templates/deployment.yaml
=> [UPDATE][devbox][0.0.6]lock image

difyfusion/Chart.yaml, difyfusion/TerminusManifest.yaml, difyfusion/templates/deployment.yaml
=> [UPDATE][difyfusion][0.0.2]lock image

difyfusionclient/Chart.yaml, difyfusionclient/TerminusManifest.yaml, difyfusionclient/templates/dify_fe_deploy.yaml
> difyfusionclient
> lock image
=> [UPDATE][difyfusionclient][0.0.3]lock image

duplicati/Chart.yaml, duplicati/TerminusManifest.yaml, duplicati/templates/deployment.yaml
=> [UPDATE][duplicati][0.0.4]lock image

farcasterhubble/Chart.yaml, farcasterhubble/TerminusManifest.yaml, farcasterhubble/templates/deployment.yaml
> farcasterhubble
> lock image
=> [UPDATE][farcasterhubble][0.0.29]lock image

firefox/Chart.yaml, firefox/TerminusManifest.yaml, firefox/templates/firefox.yaml
=> [UPDATE][firefox][0.0.4]lock image

gaianetai/Chart.yaml, gaianetai/TerminusManifest.yaml, gaianetai/templates/deployment.yaml
=> [UPDATE][gaianetai][0.0.6]lock image

geth/Chart.yaml, geth/TerminusManifest.yaml, geth/templates/geth.yaml, geth/templates/traefik.yaml
=> [UPDATE][geth][0.0.3]lock image

gitlabfusion/Chart.yaml, gitlabfusion/TerminusManifest.yaml, gitlabfusion/templates/clientproxy.yaml, gitlabfusion/templates/gitlab.yaml, gitlabfusion/templates/serverproxy.yaml
=> [UPDATE][gitlabfusion][0.1.0]lock image

gitlabfusionclient/Chart.yaml, gitlabfusionclient/TerminusManifest.yaml, gitlabfusionclient/templates/clientproxy.yaml
> gitlabfusionclient
> lock image
=> [UPDATE][gitlabfusionclient][0.0.28]lock image

gitlabpure/Chart.yaml, gitlabpure/TerminusManifest.yaml, gitlabpure/templates/gitlab.yaml
=> [UPDATE][gitlabpure][0.0.50]lock image

r4entertainment/Chart.yaml, r4entertainment/TerminusManifest.yaml, r4entertainment/templates/embedding.yaml, r4entertainment/templates/prerank.yaml
r4entertainment
upgrade prerank and embedding
=> [UPDATE][r4entertainment][0.1.38]upgrade prerank and embedding

homeassistant/Chart.yaml, homeassistant/TerminusManifest.yaml, homeassistant/templates/deployment.yaml
=> [UPDATE][homeassistant][0.0.15]lock image

immich/Chart.yaml, immich/TerminusManifest.yaml, immich/templates/machine-learning.yaml, immich/templates/server.yaml
=> [UPDATE][immich][0.0.16]lock image

ipfs/Chart.yaml, ipfs/TerminusManifest.yaml, ipfs/templates/deployment.yaml
=> [UPDATE][ipfs][0.0.31]lock image

jellyfin/Chart.yaml, jellyfin/TerminusManifest.yaml, jellyfin/templates/deployment.yaml
=> [UPDATE][jellyfin][0.0.12]lock image

lidarr/Chart.yaml, lidarr/TerminusManifest.yaml, lidarr/templates/deployment.yaml
=> [UPDATE][lidarr][0.0.4]lock image

mastodon/Chart.yaml, mastodon/TerminusManifest.yaml, mastodon/templates/apache/deployment.yaml, mastodon/templates/deployment-mastodon-sidekiq.yaml, mastodon/templates/deployment-mastodon-streaming.yaml, mastodon/templates/deployment-mastodon.yaml, mastodon/templates/elasticsearch/statefulset.yaml, mastodon/templates/job-mastodon-init.yaml, mastodon/templates/minio/deployment.yaml, mastodon/templates/minio/job-mastodon-minio-provisioning.yaml, mastodon/templates/postgresql/statefulset.yaml, mastodon/templates/redis/statefulset.yaml
=> [UPDATE][mastodon][0.0.47]lock image

mattermost/Chart.yaml, mattermost/TerminusManifest.yaml, mattermost/templates/mattermost.yaml
=> [UPDATE][mattermost][0.0.7]lock image

miniflux/Chart.yaml, miniflux/TerminusManifest.yaml, miniflux/templates/db-deployment.yaml, miniflux/templates/miniflux-deployment.yaml
=> [UPDATE][miniflux][0.0.4]lock image

n8n/Chart.yaml, n8n/TerminusManifest.yaml, n8n/templates/n8n.yaml
=> [UPDATE][n8n][0.0.9]lock image

navidrome/Chart.yaml, navidrome/TerminusManifest.yaml, navidrome/templates/deployment.yaml
=> [UPDATE][navidrome][0.0.8]lock image

nextcloud/Chart.yaml, nextcloud/TerminusManifest.yaml, nextcloud/templates/deployment.yaml
=> [UPDATE][nextcloud][0.0.14]lock image

nocodb/Chart.yaml, nocodb/TerminusManifest.yaml, nocodb/templates/deployment.yaml
=> [UPDATE][nocodb][0.0.10]lock image

nostream/Chart.yaml, nostream/TerminusManifest.yaml, nostream/templates/deployment.yaml
=> [UPDATE][nostream][0.0.7]lock image

novella/Chart.yaml, novella/TerminusManifest.yaml, novella/templates/deployment.yaml
=> [UPDATE][novella][0.0.14]lock image

nzbget/Chart.yaml, nzbget/TerminusManifest.yaml, nzbget/templates/deployment.yaml
=> [UPDATE][nzbget][0.0.9]lock image

obsidian/Chart.yaml, obsidian/TerminusManifest.yaml, obsidian/templates/deployment.yaml
=> [UPDATE][obsidian][0.0.15]lock image

ollama/Chart.yaml, ollama/TerminusManifest.yaml, ollama/templates/deployment.yaml, ollama/templates/openwebui.yaml
=> [UPDATE][ollama][0.0.13]lock image

onlyoffice/Chart.yaml, onlyoffice/TerminusManifest.yaml, onlyoffice/templates/deployment.yaml
=> [UPDATE][onlyoffice][0.0.10]lock image

openedaispeech/Chart.yaml, openedaispeech/TerminusManifest.yaml, openedaispeech/templates/deployment.yaml
=> [UPDATE][openedaispeech][0.0.8]lock image

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml, openwebui/templates/deployment.yaml
=> [UPDATE][openwebui][0.0.14]lock image

penpot/Chart.yaml, penpot/TerminusManifest.yaml, penpot/templates/backend/deployment.yaml, penpot/templates/exporter/deployment.yaml, penpot/templates/frontend/deployment.yaml, penpot/templates/redis/deployment.yaml
=> [UPDATE][penpot][0.0.4]lock image

photoprism/Chart.yaml, photoprism/TerminusManifest.yaml, photoprism/templates/deployment.yaml
=> [UPDATE][photoprism][0.0.5]lock image

photoview/Chart.yaml, photoview/TerminusManifest.yaml, photoview/templates/deployment.yaml
=> [UPDATE][photoview][0.0.3]lock image

prowlarr/Chart.yaml, prowlarr/TerminusManifest.yaml, prowlarr/templates/deployment.yaml
=> [UPDATE][prowlarr][0.0.12]lock image

qbittorrent/Chart.yaml, qbittorrent/TerminusManifest.yaml, qbittorrent/templates/deployment.yaml
=> [UPDATE][qbittorrent][0.0.11]lock image

radarr/Chart.yaml, radarr/TerminusManifest.yaml, radarr/templates/deployment.yaml
=> [UPDATE][radarr][0.0.10]lock image

radicale/Chart.yaml, radicale/TerminusManifest.yaml, radicale/templates/all.yaml
=> [UPDATE][radicale][0.0.3]lock image

readarr/Chart.yaml, readarr/TerminusManifest.yaml, readarr/templates/deployment.yaml
=> [UPDATE][readarr][0.0.7]lock image

rsshub/Chart.yaml, rsshub/TerminusManifest.yaml, rsshub/templates/browser-less-deployment.yaml, rsshub/templates/redis-deployment.yaml, rsshub/templates/rsshub-deployment.yaml
=> [UPDATE][rsshub][0.0.2]lock image

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml, sdwebui/templates/deployment.yaml
=> [UPDATE][sdwebui][0.0.8]lock image

searxng/Chart.yaml, searxng/TerminusManifest.yaml, searxng/templates/deployment.yaml
=> [UPDATE][searxng][0.0.15]lock image

showdoc/Chart.yaml, showdoc/TerminusManifest.yaml, showdoc/templates/showdoc.yaml
=> [UPDATE][showdoc][0.0.6]lock image

sickchill/Chart.yaml, sickchill/TerminusManifest.yaml, sickchill/templates/deployment.yaml
=> [UPDATE][sickchill][0.0.4]lock image

transmission/Chart.yaml, transmission/TerminusManifest.yaml, transmission/templates/deployment.yaml
=> [UPDATE][transmission][0.0.6]lock image

whisper/Chart.yaml, whisper/TerminusManifest.yaml, whisper/templates/deployment.yaml
=> [UPDATE][whisper][0.0.7]lock image

wordpress/Chart.yaml, wordpress/TerminusManifest.yaml, wordpress/templates/proxy.yaml, wordpress/templates/wordpress.yaml
=> [UPDATE][wordpress][0.0.16]lock image

immich/Chart.yaml, immich/TerminusManifest.yaml, immich/templates/machine-learning.yaml, immich/templates/server.yaml
> immich
> Add Redis within the application
=> [UPDATE][immich][0.0.20]Add Redis within the application

onlyoffice/Chart.yaml, onlyoffice/TerminusManifest.yaml, onlyoffice/templates/deployment.yaml
> onlyoffice
> add example web
=> [UPDATE][onlyoffice][0.0.23]add example web

immich/Chart.yaml, immich/TerminusManifest.yaml, immich/templates/server.yaml
=> [UPDATE][immich][0.0.21]fix redis host

photoprism/Chart.yaml, photoprism/TerminusManifest.yaml, photoprism/templates/deployment.yaml
> photoprism
> update AUTH_MODE to public
=> [UPDATE][photoprism][0.0.6]update AUTH_MODE to public

prometheusclient/.helmignore, prometheusclient/Chart.yaml, prometheusclient/TerminusManifest.yaml, prometheusclient/i18n/zh/TerminusManifest.yaml, prometheusclient/owners, prometheusclient/templates/deployment.yaml, prometheusclient/values.yaml
prometheus client
Prometheus, a Cloud Native Computing Foundation project, is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts when specified conditions are observed.
=> [NEW][prometheusclient][0.0.3]add prometheusclient

comfyuiclient/Chart.yaml, comfyuiclient/TerminusManifest.yaml, comfyuiclient/i18n/zh/TerminusManifest.yaml, comfyuiclient/owners, comfyuiclient/templates/clientproxy.yaml
> comfyuiclient
> comfyui client release version first
=> [NEW][comfyuiclient][0.0.3]comfyui client release version first

searxng/Chart.yaml, searxng/TerminusManifest.yaml, searxng/templates/clientproxy.yaml, searxng/templates/deployment.yaml
=> [UPDATE][searxng][0.1.3]change to CS

gaianetai/Chart.yaml, gaianetai/TerminusManifest.yaml, gaianetai/templates/deployment.yaml
=> [UPDATE][gaianetai][0.1.1]change to CS

gaianetaiclient/Chart.yaml, gaianetaiclient/TerminusManifest.yaml, gaianetaiclient/i18n/zh/TerminusManifest.yaml, gaianetaiclient/owners, gaianetaiclient/templates/clientproxy.yaml
> gaianetaiclient
> new app gaianetai client
=> [NEW][gaianetaiclient][0.0.1]gaianetai client

immichclient/Chart.yaml, immichclient/TerminusManifest.yaml, immichclient/i18n/zh/TerminusManifest.yaml, immichclient/owners, immichclient/templates/clientproxy.yaml
> immichclient
> new app immich client
=> [NEW][immichclient][0.0.3]new app immich client

immich/Chart.yaml, immich/TerminusManifest.yaml, immich/templates/server.yaml
=> [UPDATE][immich][0.1.0]change to CS

openedaispeech/Chart.yaml, openedaispeech/TerminusManifest.yaml, openedaispeech/templates/deployment.yaml
> openedaispeech
> change to CS
=> [UPDATE][openedaispeech][0.1.0]change to CS

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml, openwebui/templates/deployment.yaml
=> [UPDATE][openwebui][0.1.1]change to CS

whisper/Chart.yaml, whisper/TerminusManifest.yaml, whisper/templates/deployment.yaml
=> [UPDATE][whisper][0.1.0]change to CS

perplexica/Chart.yaml, perplexica/TerminusManifest.yaml, perplexica/templates/backend.yaml, perplexica/templates/frontend.yaml, perplexica/templates/ingress.yaml
=> [UPDATE][perplexica][0.1.6]change to CS

whisperclient/Chart.yaml, whisperclient/TerminusManifest.yaml, whisperclient/i18n/zh/TerminusManifest.yaml, whisperclient/owners, whisperclient/templates/clientproxy.yaml
> whisperclient
> client for whisper
=> [NEW][whisperclient][0.0.1]client for whisper

difyfusion/Chart.yaml, difyfusion/TerminusManifest.yaml
=> [UPDATE][difyfusion][0.0.3]fix i18n

prometheusclient/Chart.yaml, prometheusclient/TerminusManifest.yaml, prometheusclient/i18n/en-US/TerminusManifest.yaml, prometheusclient/i18n/zh-CN/TerminusManifest.yaml
> 
> 
> 
> 
Prometheus
fix i18n title
=> [UPDATE][prometheusclient][0.0.4]fix i18n title

comfyuiclient/Chart.yaml, comfyuiclient/TerminusManifest.yaml
ComfyUI
change auth level to internal
=> [UPDATE][comfyuiclient][0.0.4]change auth level to internal

ollama/Chart.yaml, ollama/TerminusManifest.yaml
> ollama
> add client perplexica
=> [UPDATE][ollama][0.1.4]add client perplexica

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> config output path to userspace
=> [UPDATE][sdwebui][0.1.16]config output path to userspace

comfyui/Chart.yaml, comfyui/TerminusManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> config output path to userspace
=> [UPDATE][comfyui][0.1.9]config output path to userspace

perplexica/Chart.yaml, perplexica/TerminusManifest.yaml, perplexica/templates/frontend.yaml
> perplexica
> fix api config in local net
=> [UPDATE][perplexica][0.1.7]fix api config in local net

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml, sdwebui/templates/deployment.yaml
=> [UPDATE][sdwebui][0.1.17]set restart type: Recreate

gaianetai/Chart.yaml, gaianetai/TerminusManifest.yaml, gaianetai/templates/deployment.yaml
=> [UPDATE][gaianetai][0.1.2]set restart type: Recreate

ollama/Chart.yaml, ollama/TerminusManifest.yaml, ollama/templates/deployment.yaml
=> [UPDATE][ollama][0.1.5]set restart type: Recreate

openedaispeech/Chart.yaml, openedaispeech/TerminusManifest.yaml, openedaispeech/templates/deployment.yaml
=> [UPDATE][openedaispeech][0.1.1]set restart type: Recreate

whisper/Chart.yaml, whisper/TerminusManifest.yaml, whisper/templates/deployment.yaml
=> [UPDATE][whisper][0.1.1]set restart type: Recreate

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> up version: 1.10.1
=> [UPDATE][sdwebui][0.1.18]up version: 1.10.1

immichclient/Chart.yaml, immichclient/TerminusManifest.yaml, immichclient/templates/clientproxy.yaml
immichclient
remove liveness probe
=>  [UPDATE][immichclient][0.0.4]fix remove liveness probe

gaianetaiclient/Chart.yaml, gaianetaiclient/TerminusManifest.yaml
=> [UPDATE][gaianetaiclient][0.0.2]fix categories

steamheadless/Chart.yaml, steamheadless/TerminusManifest.yaml, steamheadless/i18n/zh/TerminusManifest.yaml, steamheadless/owners, steamheadless/templates/steam.yaml
> steamheadless
> new app steamheadless
=> [NEW][steamheadless][0.0.7]new app steamheadless

openwebui/Chart.yaml, openwebui/TerminusManifest.yaml, openwebui/templates/deployment.yaml
> openwebui
> preinstall model
=> [UPDATE][openwebui][0.1.2]preinstall model

steamheadless/Chart.yaml, steamheadless/TerminusManifest.yaml, steamheadless/i18n/en-US/TerminusManifest.yaml, steamheadless/i18n/zh-CN/TerminusManifest.yaml, steamheadless/i18n/zh/TerminusManifest.yaml
=> [UPDATE][steamheadless][0.0.8]fix i18n

sdwebui/Chart.yaml, sdwebui/TerminusManifest.yaml, sdwebui/templates/deployment.yaml
=> [UPDATE][sdwebui][0.1.19]config probe

sdwebuiclient/Chart.yaml, sdwebuiclient/TerminusManifest.yaml, sdwebuiclient/templates/clientproxy.yaml
> sdwebuiclient
> config readiness probe
=> [UPDATE][sdwebuiclient][0.0.9]config readiness probe

comfyui/Chart.yaml, comfyui/TerminusManifest.yaml, comfyui/templates/configmap.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][0.1.10]config probe

comfyuiclient/Chart.yaml, comfyuiclient/TerminusManifest.yaml, comfyuiclient/templates/clientproxy.yaml
> comfyuiclient
> config probe
=> [UPDATE][comfyuiclient][0.0.5]config probe

steamheadless/Chart.yaml, steamheadless/TerminusManifest.yaml, steamheadless/templates/steam.yaml
> steamheadless
> config probe
=> [UPDATE][steamheadless][0.0.10]config probe

firefox/Chart.yaml, firefox/TerminusManifest.yaml, firefox/templates/firefox.yaml
> firefox
> support language cn
=> [UPDATE][firefox][0.0.7]support language cn

onlyoffice/Chart.yaml, onlyoffice/TerminusManifest.yaml, onlyoffice/templates/deployment.yaml
> onlyoffice
> change to cs architecture
=> [UPDATE][onlyoffice][0.0.36]change to cs architecture

onlyofficeclient/Chart.yaml, onlyofficeclient/TerminusManifest.yaml, onlyofficeclient/i18n/en-US/TerminusManifest.yaml, onlyofficeclient/i18n/zh-CN/TerminusManifest.yaml, onlyofficeclient/owners, onlyofficeclient/templates/client.yaml, onlyofficeclient/templates/proxy.yaml
> onlyofficeclient
> new app onlyofice web
=> [NEW][onlyofficeclient][0.0.19]new app onlyofice web

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/configmap.yaml, comfyui/templates/deployment.yaml
comfyui
update version to 0.2.x
=> [UPDATE][comfyui][1.0.5]update version to 0.2.x 

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> update probe config
=> [UPDATE][sdwebui][1.0.1]update probe config

navidrome/Chart.yaml, navidrome/OlaresManifest.yaml, navidrome/templates/deployment.yaml
=> [UPDATE][navidrome][1.0.1]fix dir user & group

showdoc/Chart.yaml, showdoc/OlaresManifest.yaml, showdoc/templates/showdoc.yaml
=> [UPDATE][showdoc][1.0.1]fix dir user & group

nzbget/Chart.yaml, nzbget/OlaresManifest.yaml, nzbget/templates/deployment.yaml
=> [UPDATE][nzbget][1.0.1]fix dir user & group

photoprism/Chart.yaml, photoprism/OlaresManifest.yaml, photoprism/templates/deployment.yaml
=> [UPDATE][photoprism][1.0.1]fix dir user & group

affine/Chart.yaml, affine/OlaresManifest.yaml, affine/templates/deployment.yaml
=> [UPDATE][affine][1.0.1]fix dir user & group

bazarr/Chart.yaml, bazarr/OlaresManifest.yaml, bazarr/templates/deployment.yaml
=> [UPDATE][bazarr][1.0.1]fix dir user & group

chinesesubfinder/Chart.yaml, chinesesubfinder/OlaresManifest.yaml, chinesesubfinder/templates/chinesesubfinder.yaml
=> [UPDATE][chinesesubfinder][1.0.1]fix dir user & group

ghost/Chart.yaml, ghost/OlaresManifest.yaml, ghost/templates/deployment.yaml
=> [UPDATE][ghost][1.0.3]fix dir user & group

homeassistant/Chart.yaml, homeassistant/OlaresManifest.yaml, homeassistant/templates/deployment.yaml
=> [UPDATE][homeassistant][1.0.2]fix dir user & group

immich/Chart.yaml, immich/OlaresManifest.yaml, immich/templates/server.yaml
=> [UPDATE][immich][1.0.2]fix dir user & group

ipfs/Chart.yaml, ipfs/OlaresManifest.yaml, ipfs/templates/deployment.yaml
=> [UPDATE][ipfs][1.0.1]fix dir user & group

jellyfin/Chart.yaml, jellyfin/OlaresManifest.yaml, jellyfin/templates/deployment.yaml
=> [UPDATE][jellyfin][1.0.2]fix dir user & group

qbittorrent/Chart.yaml, qbittorrent/OlaresManifest.yaml, qbittorrent/templates/deployment.yaml
=> [UPDATE][qbittorrent][1.0.1]fix dir user & group

sickchill/Chart.yaml, sickchill/OlaresManifest.yaml, sickchill/templates/deployment.yaml
=> [UPDATE][sickchill][1.0.1]fix dir user & group

obsidian/Chart.yaml, obsidian/OlaresManifest.yaml, obsidian/templates/deployment.yaml
=> [UPDATE][obsidian][1.0.1]fix dir user & group

nextcloud/Chart.yaml, nextcloud/OlaresManifest.yaml, nextcloud/templates/deployment.yaml
=> [UPDATE][nextcloud][1.0.2]fix dir user & group

nocodb/Chart.yaml, nocodb/OlaresManifest.yaml, nocodb/templates/deployment.yaml
=> [UPDATE][nocodb][1.0.1]fix dir user & group

farcasterhubble/Chart.yaml, farcasterhubble/OlaresManifest.yaml, farcasterhubble/templates/deployment.yaml
=> [UPDATE][farcasterhubble][1.0.1]fix dir user & group

gaianetai/Chart.yaml, gaianetai/OlaresManifest.yaml, gaianetai/templates/deployment.yaml
=> [UPDATE][gaianetai][1.0.1]fix dir user & group

geth/Chart.yaml, geth/OlaresManifest.yaml, geth/templates/geth.yaml
=> [UPDATE][geth][1.0.1]fix dir user & group

ollama/Chart.yaml, ollama/OlaresManifest.yaml, ollama/templates/deployment.yaml
=> [UPDATE][ollama][1.0.1]fix dir user & group

openwebui/Chart.yaml, openwebui/OlaresManifest.yaml, openwebui/templates/deployment.yaml
=> [UPDATE][openwebui][1.0.1]fix dir user & group

perplexica/Chart.yaml, perplexica/OlaresManifest.yaml, perplexica/templates/backend.yaml
=> [UPDATE][perplexica][1.0.2]fix dir user & group

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
=> [UPDATE][sdwebui][1.0.2]fix dir user & group

searxng/Chart.yaml, searxng/OlaresManifest.yaml, searxng/templates/deployment.yaml
> searxng
> remove app cache dir
=> [UPDATE][searxng][1.0.1]remove app cache dir

whisper/Chart.yaml, whisper/OlaresManifest.yaml, whisper/templates/deployment.yaml
=> [UPDATE][whisper][1.0.1]fix dir user & group

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][1.0.6]config output dir

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
=> [UPDATE][sdwebui][1.0.3]config output dir

cmproxy/Chart.yaml, cmproxy/OlaresManifest.yaml, cmproxy/README.md, cmproxy/i18n/en-US/OlaresManifest.yaml, cmproxy/i18n/zh-CN/OlaresManifest.yaml, cmproxy/owners, cmproxy/templates/proxy.yaml
> cmproxy
> new app chatgpt-web-midjourney-proxy
=> [NEW][cmproxy][1.0.0]new app chatgpt-web-midjourney-proxy

wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/wordpress.yaml
> wordpress
> fix create root dir by subPath
=> [UPDATE][wordpress][1.0.2]fix create root dir by subPath

sickchill/Chart.yaml, sickchill/OlaresManifest.yaml, sickchill/templates/deployment.yaml
> sickchill
> fix create root dir by subPath
=> [UPDATE][sickchill][1.0.2]fix create root dir by subPath

transmission/Chart.yaml, transmission/OlaresManifest.yaml, transmission/templates/deployment.yaml
> transmission
> fix create root dir by subPath
=> [UPDATE][transmission][1.0.2]fix create root dir by subPath

openwebui/Chart.yaml, openwebui/OlaresManifest.yaml, openwebui/templates/deployment.yaml
=> [UPDATE][openwebui][1.0.2]fix user 1000

stablefast3d/.helmignore, stablefast3d/Chart.yaml, stablefast3d/OlaresManifest.yaml, stablefast3d/i18n/en-US/OlaresManifest.yaml, stablefast3d/i18n/zh-CN/OlaresManifest.yaml, stablefast3d/owners, stablefast3d/templates/deployment.yaml, stablefast3d/values.yaml
> stablefast3d
> new app stable-fast-3d
=> [NEW][stablefast3d][1.0.5]new app stable-fast-3d

stablefast3dclient/Chart.yaml, stablefast3dclient/OlaresManifest.yaml, stablefast3dclient/i18n/en-US/OlaresManifest.yaml, stablefast3dclient/i18n/zh-CN/OlaresManifest.yaml, stablefast3dclient/owners, stablefast3dclient/templates/clientproxy.yaml
> stablefast3dclient
> new app stable-fast-3d-client
=> [NEW][stablefast3dclient][1.0.0]new app stable-fast-3d-client

cmproxy/Chart.yaml, cmproxy/OlaresManifest.yaml
ChatGPT Web Midjourney Proxy
add run as user
fix os depend version
=> [UPDATE][cmproxy][1.0.1]add run as user

hasura/Chart.yaml, hasura/OlaresManifest.yaml
hasura
fix os dependency version
=> [UPDATE][hasura][1.0.1]fix os dependency version

comfyuiclient/Chart.yaml, comfyuiclient/OlaresManifest.yaml, comfyuiclient/templates/clientproxy.yaml
> comfyuiclient
> remove header X-Frame-Options SAMEORIGIN
=> [UPDATE][comfyuiclient][1.0.1]remove header X-Frame-Options SAMEORIGIN

hasura/Chart.yaml, hasura/OlaresManifest.yaml
hasura
remove mongodb requirement
=> [UPDATE][hasura][1.0.2]fix middleware requirement

ollama/Chart.yaml, ollama/OlaresManifest.yaml
> ollama
> fix olares min version
=> [UPDATE][ollama][1.0.4]fix ollama dependencies min version

steamheadless/Chart.yaml, steamheadless/OlaresManifest.yaml, steamheadless/templates/steam.yaml
> steamheadless
> support sunshine
=> [UPDATE][steamheadless][1.0.4]support sunshine

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> Change the output folder to non-root permissions.
=> [UPDATE][comfyui][1.0.9]Change the output folder to non-root permissions.

ollama/Chart.yaml, ollama/OlaresManifest.yaml, ollama/templates/deployment.yaml
=> [UPDATE][ollama][1.0.5]support cpu

ollama/Chart.yaml, ollama/OlaresManifest.yaml, ollama/templates/deployment.yaml
> ollama
> support cpu on 1.11
=> [UPDATE][ollama][1.0.6]support cpu on 1.11

perplexica/Chart.yaml, perplexica/OlaresManifest.yaml
perplexica
change open method to window
=> [UPDATE][perplexica][1.0.3]change open method

firefox/Chart.yaml, firefox/OlaresManifest.yaml, firefox/templates/firefox.yaml
Firefox
enhance application stability
=> [UPDATE][firefox][1.0.1]enhance application stability

whisper/Chart.yaml, whisper/OlaresManifest.yaml
Faster Whisper For Cluster
set run as user
=> [UPDATE][whisper][1.0.2]run as user

searxngclient/Chart.yaml, searxngclient/OlaresManifest.yaml
=> [UPDATE][searxngclient][1.0.1]run as user

chinesesubfinder/Chart.yaml, chinesesubfinder/OlaresManifest.yaml
=> [UPDATE][chinesesubfinder][1.0.2]run as user

mattermost/Chart.yaml, mattermost/OlaresManifest.yaml
=>  [UPDATE][mattermost][1.0.1]add run as user

miniflux/Chart.yaml, miniflux/OlaresManifest.yaml
=> [UPDATE][miniflux][1.0.1]add run as user

sickchill/Chart.yaml, sickchill/OlaresManifest.yaml
=> [UPDATE][sickchill][1.0.3]run as user

showdoc/Chart.yaml, showdoc/OlaresManifest.yaml
=> [UPDATE][showdoc][1.0.2]run as user

rsshub/Chart.yaml, rsshub/OlaresManifest.yaml
rsshub
change auth level to `internal`
run as user
=> [UPDATE][rsshub][1.0.1]change auth level and run as user

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/i18n/en-US/OlaresManifest.yaml, comfyui/i18n/zh-CN/OlaresManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> update version to 0.3.9
=> [UPDATE][comfyui][1.0.13]update version to 0.3.9

hunyuan3d/Chart.yaml, hunyuan3d/OlaresManifest.yaml
=> [UPDATE][hunyuan3d][1.0.2]fix entrance title

otmoiclp/Chart.yaml, otmoiclp/OlaresManifest.yaml
=> [UPDATE][otmoiclp][1.0.3]update website

ollama/Chart.yaml, ollama/OlaresManifest.yaml, ollama/templates/deployment.yaml
> ollama
> change model save path to sharedlib
=> [UPDATE][ollama][1.0.7]change model save path to sharedlib

onlyofficeclient/Chart.yaml, onlyofficeclient/OlaresManifest.yaml
> onlyofficeclient
> fix policies config
=> [UPDATE][onlyofficeclient][1.0.1]fix policies config

onlyoffice/Chart.yaml, onlyoffice/OlaresManifest.yaml
> onlyoffice
> config requiredMemory
=> [UPDATE][onlyoffice][1.0.1]config requiredMemory

difyfusion/Chart.yaml, difyfusion/OlaresManifest.yaml, difyfusion/i18n/en-US/OlaresManifest.yaml, difyfusion/i18n/zh-CN/OlaresManifest.yaml
> 
> [UPDATE][difyfusion][1.0.2]fix i18n
> 
> 
difyfusion
fix i18n
=> [UPDATE][difyfusion][1.0.2]fix i18n

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> up version to 0.3.10
=> [UPDATE][comfyui][1.0.15]up version to 0.3.10

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> config HF_ENDPOINT
=> [UPDATE][sdwebui][1.0.4]config HF_ENDPOINT

wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/wordpress.yaml
> wordpress
> Relaxation of installation deadline
=> [UPDATE][wordpress][1.0.5]Relaxation of installation deadline

ollama/Chart.yaml, ollama/OlaresManifest.yaml
=> [UPDATE][ollama][1.0.8]new client n8n

n8n/Chart.yaml, n8n/OlaresManifest.yaml
=> [UPDATE][n8n][1.0.2]new service ollama

awesomedigitalhuman/Chart.yaml, awesomedigitalhuman/OlaresManifest.yaml, awesomedigitalhuman/i18n/en-US/OlaresManifest.yaml, awesomedigitalhuman/i18n/zh-CN/OlaresManifest.yaml, awesomedigitalhuman/owners, awesomedigitalhuman/templates/config.yaml, awesomedigitalhuman/templates/deployment.yaml
> awesomedigitalhuman
> new app Awesome Digital Human
=> [NEW][awesomedigitalhuman][1.0.2]new app Awesome Digital Human

onlyofficeclient/Chart.yaml, onlyofficeclient/OlaresManifest.yaml
onlyofficeclient
add dependencies mandatory
=> [UPDATE][onlyofficeclient][1.0.2]add dependencies mandatory

stablefast3dclient/Chart.yaml, stablefast3dclient/OlaresManifest.yaml
stablefast3dclient
add dependencies mandatory
=>  [UPDATE][stablefast3dclient][1.0.1]add dependencies mandatory

whisperclient/Chart.yaml, whisperclient/OlaresManifest.yaml
whisperclient
add dependencies mandatory
=> [UPDATE][whisperclient][1.0.1]add dependencies mandatory

hunyuan3dclient/Chart.yaml, hunyuan3dclient/OlaresManifest.yaml
hunyuan3dclient
add dependencies mandatory
=> [UPDATE][hunyuan3dclient][1.0.1]add dependencies mandatory

awesomedigitalhuman/Chart.yaml, awesomedigitalhuman/OlaresManifest.yaml, awesomedigitalhuman/i18n/en-US/OlaresManifest.yaml, awesomedigitalhuman/i18n/zh-CN/OlaresManifest.yaml
Awesome Digital Human
update description
=> [UPDATE][awesomedigitalhuman][1.0.3]update description

n8n/Chart.yaml, n8n/OlaresManifest.yaml, n8n/templates/n8n.yaml
=> [UPDATE][n8n][1.0.3]fix config path

wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/proxy.yaml
=> [UPDATE][wordpress][1.0.6]update proxy cpu limit

wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/proxy.yaml
> wordpress
> made proxy support local network
> made proxy faster
=> [UPDATE][wordpress][1.0.8]made proxy support local network

wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/secret.yaml, wordpress/templates/wordpress.yaml
> wordpress
> Resolve the lost secret issue.
=> [UPDATE][wordpress][1.0.9]Resolve the lost secret issue.

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> Update the permissions for the AI directory to 1000
=> [UPDATE][sdwebui][1.0.5]Update the permissions for the AI directory to 1000

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> fix comfyui manager
=> [UPDATE][comfyui][1.0.16]fix comfyui manager

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][1.0.17]fix web version

chromium/Chart.yaml, chromium/OlaresManifest.yaml, chromium/templates/chromium.yaml
=> [UPDATE][chromium][1.0.1]Support Chinese

ollama/Chart.yaml, ollama/OlaresManifest.yaml
=> [UPDATE][ollama][1.0.9]Change Ollama Entrance to internal

ollama/Chart.yaml, ollama/OlaresManifest.yaml
ollama
add appRef ragflow and lobechat
=> [UPDATE][ollama][1.0.10]add appRef

otmoiclp/Chart.yaml, otmoiclp/OlaresManifest.yaml, otmoiclp/templates/admin.yaml, otmoiclp/templates/amm.yaml, otmoiclp/templates/dashboard.yaml, otmoiclp/templates/lpnode.yaml, otmoiclp/templates/market.yaml
> otmoiclp
> support custom token
=> [UPDATE][otmoiclp][1.0.6]support custom token

sdwebuiforgeforcluster/.helmignore, sdwebuiforgeforcluster/Chart.yaml, sdwebuiforgeforcluster/OlaresManifest.yaml, sdwebuiforgeforcluster/i18n/en-US/OlaresManifest.yaml, sdwebuiforgeforcluster/i18n/zh-CN/OlaresManifest.yaml, sdwebuiforgeforcluster/owners, sdwebuiforgeforcluster/templates/deployment.yaml, sdwebuiforgeforcluster/templates/entrances.yaml, sdwebuiforgeforcluster/values.yaml
> sdwebuiforgeforcluster
> new app sd webui forge
=> [NEW][sdwebuiforgeforcluster][1.0.3]new app sd webui forge

comfyuiclient/Chart.yaml, comfyuiclient/OlaresManifest.yaml, comfyuiclient/templates/clientproxy.yaml
=> [UPDATE][comfyuiclient][1.0.5]relax probe

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/clientproxy.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][1.1.1]no envoy

qinglong/Chart.yaml, qinglong/OlaresManifest.yaml, qinglong/i18n/en-US/OlaresManifest.yaml, qinglong/i18n/zh-CN/OlaresManifest.yaml, qinglong/owners, qinglong/templates/qinglong.yaml
> Qinglong
> Timed task management platform supporting Python3, JavaScript, Shell, Typescript. 
>
=> [NEW][qinglong][0.0.1]New app Qinglong

windows/Chart.yaml, windows/OlaresManifest.yaml, windows/templates/deployment.yaml
Windows
fix version, resource and entrance title
=> [UPDATE][windows][1.0.1]fix version, resource and entrance title

sdwebuiclient/Chart.yaml, sdwebuiclient/OlaresManifest.yaml, sdwebuiclient/templates/clientproxy.yaml
=> [UPDATE][sdwebuiclient][1.0.3]relax probe

ollama/Chart.yaml, ollama/OlaresManifest.yaml, ollama/templates/deployment.yaml
> ollama
> Bidirectional mount
=> [UPDATE][ollama][1.0.11]Bidirectional mount

sdwebuiforgeforcluster/Chart.yaml, sdwebuiforgeforcluster/OlaresManifest.yaml, sdwebuiforgeforcluster/templates/deployment.yaml
> sdwebuiforgeforcluster
> update config global.index-url
=> [UPDATE][sdwebuiforgeforcluster][1.0.4]update config global.index-url

sdwebuiforgeforcluster/Chart.yaml, sdwebuiforgeforcluster/OlaresManifest.yaml, sdwebuiforgeforcluster/templates/deployment.yaml
> sdwebuiforgeforcluster
> fix env HOME
=> [UPDATE][sdwebuiforgeforcluster][1.0.5]fix env HOME

ragflow/Chart.yaml, ragflow/OlaresManifest.yaml
ragflow
add system data requirement
=>  [UPDATE][ragflow][1.0.5]add system data requirement

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> Improve the robustness of initcache phase commands
=> [UPDATE][sdwebui][1.0.8]Improve the robustness of initcache phase commands

wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/proxy.yaml
> wordpress
> fix plugin use http
=> [UPDATE][wordpress][1.0.10]fix plugin use http

memos/.helmignore, memos/Chart.yaml, memos/OlaresManifest.yaml, memos/i18n/en-US/OlaresManifest.yaml, memos/i18n/zh-CN/OlaresManifest.yaml, memos/owners, memos/templates/memos.yaml, memos/values.yaml
> Memos
> Memos is a privacy-first, lightweight note-taking solution that allows you to effortlessly capture and share your ideas.
=> [NEW][memos][1.0.1]new app memos

gitlabfusion/Chart.yaml, gitlabfusion/OlaresManifest.yaml, gitlabfusion/templates/clientproxy.yaml, gitlabfusion/templates/entrances.yaml, gitlabfusion/templates/gitlab.yaml, gitlabfusion/templates/serverproxy.yaml
> gitlabfusion
> Fixed the issue of timeout when creating an account in a poor network environment
=> [UPDATE][gitlabfusion][1.0.4]fix create account

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> update output path
=> [UPDATE][sdwebui][1.0.9]update output path

xinference/Chart.yaml, xinference/OlaresManifest.yaml, xinference/i18n/en-US/OlaresManifest.yaml, xinference/i18n/zh-CN/OlaresManifest.yaml, xinference/owners, xinference/templates/clientproxy.yaml, xinference/templates/deployment.yaml
> xinference
> new app xinference
=> [NEW][xinference][1.0.8]new app xinference

openwebui/Chart.yaml, openwebui/OlaresManifest.yaml, openwebui/templates/deployment.yaml
> openwebui
> support xinference
=> [UPDATE][openwebui][1.0.5]support xinference

xinference/Chart.yaml, xinference/OlaresManifest.yaml
Xinference
fix entrance auth level
=> [UPDATE][xinference][1.0.9]fix entrance auth level

directus/.helmignore, directus/Chart.yaml, directus/OlaresManifest.yaml, directus/i18n/en-US/OlaresManifest.yaml, directus/i18n/zh-CN/OlaresManifest.yaml, directus/owners, directus/templates/directus.yaml, directus/templates/redis/deployment.yaml, directus/templates/redis/service.yaml, directus/values.yaml
=> [NEW][directus][1.0.1]new app directus

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> fix protobuf version
=> [UPDATE][comfyui][1.1.3]fix protobuf version

windows/Chart.yaml, windows/OlaresManifest.yaml, windows/templates/deployment.yaml
> windows
> fix: support igpu passthrough;iso use cdn url
>
=> [UPDATE][windows][1.0.3]fix: support igpu passthrough;iso use cdn url

llamafactory/Chart.yaml, llamafactory/OlaresManifest.yaml, llamafactory/i18n/en-US/OlaresManifest.yaml, llamafactory/i18n/zh-CN/OlaresManifest.yaml, llamafactory/owners, llamafactory/templates/clientproxy.yaml, llamafactory/templates/deployment.yaml
> llamafactory
> new app llamafactory
=> [NEW][llamafactory][1.0.4]new app llamafactory

windows/Chart.yaml, windows/OlaresManifest.yaml
> windows
> fix: add tailscale acls
>
=> [UPDATE][windows][1.0.4]fix: add tailscale acls

halo/.helmignore, halo/Chart.yaml, halo/OlaresManifest.yaml, halo/i18n/en-US/OlaresManifest.yaml, halo/i18n/zh-CN/OlaresManifest.yaml, halo/owners, halo/templates/deployment.yaml, halo/values.yaml
> Halo
> Powerful and easy-to-use open source website building tool.
=> [NEW][halo][1.0.2]new app halo

windows/Chart.yaml, windows/OlaresManifest.yaml, windows/templates/deployment.yaml
> windows
> fix: change windows iso
=> [UPDATE][windows][1.0.5]fix: change windows iso

llamafactory/Chart.yaml, llamafactory/OlaresManifest.yaml, llamafactory/i18n/en-US/OlaresManifest.yaml, llamafactory/i18n/zh-CN/OlaresManifest.yaml
llamafactory
fix description and entrance auth level
=> [UPDATE][llamafactory][1.0.5]fix description and entrance auth level

stirlingpdf/Chart.yaml, stirlingpdf/OlaresManifest.yaml, stirlingpdf/i18n/zh-CN/OlaresManifest.yaml
> Stirling-PDF.
> update title and description
=> [UPDATE][stirlingpdf][1.0.2] update title

photoview/Chart.yaml, photoview/OlaresManifest.yaml, photoview/templates/deployment.yaml
> photoview
> fix launch permissions
=> [UPDATE][photoview][1.0.1]fix launch permissions

windows/Chart.yaml, windows/OlaresManifest.yaml, windows/templates/deployment.yaml
> windows
> fix: disable igpu passthrouth
=> [UPDATE][windows][1.0.6]fix: disable igpu passthrouth

lobechat/Chart.yaml, lobechat/OlaresManifest.yaml, lobechat/i18n/en-US/OlaresManifest.yaml, lobechat/i18n/zh-CN/OlaresManifest.yaml, lobechat/templates/lobechat.yaml
=> [UPDATE][lobechat][0.0.2]upgrade to 1.68.1

windows/Chart.yaml, windows/OlaresManifest.yaml, windows/templates/deployment.yaml
=> [UPDATE][windows][1.0.7]fix: igpu enable

uptimekuma/.helmignore, uptimekuma/Chart.yaml, uptimekuma/OlaresManifest.yaml, uptimekuma/i18n/en-US/OlaresManifest.yaml, uptimekuma/i18n/zh-CN/OlaresManifest.yaml, uptimekuma/owners, uptimekuma/templates/uptimekuma.yaml
> Uptime Kuma.
> new app uptimekuma.
=> [NEW][uptimekuma][1.0.1]new app uptimekuma

listmonk/Chart.yaml, listmonk/OlaresManifest.yaml
=> [UPDATE][listmonk][1.0.3]add promoteImage

docmost/Chart.yaml, docmost/OlaresManifest.yaml
=> [UPDATE][docmost][1.0.2]add promoteImage

directus/Chart.yaml, directus/OlaresManifest.yaml
=>  [UPDATE][directus][1.0.4]add promoteImage

coder/.helmignore, coder/Chart.yaml, coder/OlaresManifest.yaml, coder/i18n/en-US/OlaresManifest.yaml, coder/i18n/zh-CN/OlaresManifest.yaml, coder/owners, coder/templates/coder.yaml, coder/values.yaml
> Coder
> Self-Hosted Cloud Development Environments.
=> [NEW][coder][1.0.1]new app coder

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/i18n/en-US/OlaresManifest.yaml, comfyui/i18n/zh-CN/OlaresManifest.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][1.1.5]support wan video

halo/Chart.yaml, halo/OlaresManifest.yaml
=> [UPDATE][halo][1.0.7]support smtp

teable/Chart.yaml, teable/OlaresManifest.yaml
=> [UPDATE][teable][1.0.2]support smtp

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
=> [UPDATE][comfyui][1.1.6]no restart

teable/Chart.yaml, teable/OlaresManifest.yaml, teable/templates/configmap.yaml, teable/templates/teable.yaml
> teable
> fix bug: upload files
=> [UPDATE][teable][1.0.3]fix upload files

comfyui/Chart.yaml, comfyui/OlaresManifest.yaml, comfyui/templates/deployment.yaml
> comfyui
> fix python repo config
=> [UPDATE][comfyui][1.1.7]fix python repo config

comfyuiclient/Chart.yaml, comfyuiclient/OlaresManifest.yaml, comfyuiclient/templates/clientproxy.yaml
> comfyuiclient
> made readiness be faster
=> [UPDATE][comfyuiclient][1.0.7]made readiness be faster

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> auto download openai clip vit large patch14
=> [UPDATE][sdwebui][1.0.10]auto download openai clip vit large patch14

sdwebui/Chart.yaml, sdwebui/OlaresManifest.yaml, sdwebui/templates/deployment.yaml
> sdwebui
> use aria2c download
=> [UPDATE][sdwebui][1.0.11]use aria2c download

alist/.helmignore, alist/Chart.yaml, alist/OlaresManifest.yaml, alist/i18n/en-US/OlaresManifest.yaml, alist/i18n/zh-CN/OlaresManifest.yaml, alist/owners, alist/templates/alist.yaml, alist/values.yaml
=> [NEW][alist][1.0.1]new app Alist

wewerss/.helmignore, wewerss/Chart.yaml, wewerss/OlaresManifest.yaml, wewerss/i18n/en-US/OlaresManifest.yaml, wewerss/i18n/zh-CN/OlaresManifest.yaml, wewerss/owners, wewerss/templates/mysql/deployment.yaml, wewerss/templates/wewerss.yaml
=> [NEW][wewerss][1.0.1]new app sewers

md/.helmignore, md/Chart.yaml, md/OlaresManifest.yaml, md/i18n/en-US/OlaresManifest.yaml, md/i18n/zh-CN/OlaresManifest.yaml, md/owners, md/templates/md.yaml, md/values.yaml
> WeChat Markdown Editor
> WeChat Markdown Editor
=> [NEW][md][1.0.1] add app md

localai/.helmignore, localai/Chart.yaml, localai/OlaresManifest.yaml, localai/i18n/en-US/OlaresManifest.yaml, localai/i18n/zh-CN/OlaresManifest.yaml, localai/owners, localai/templates/configmap.yaml, localai/templates/localai.yaml, localai/values.yaml
> localai
> LocalAI is the free, Open Source OpenAI alternative
=> [NEW][localai][1.0.1] add app LocalAI

flowise/.helmignore, flowise/Chart.yaml, flowise/OlaresManifest.yaml, flowise/i18n/en-US/OlaresManifest.yaml, flowise/i18n/zh-CN/OlaresManifest.yaml, flowise/owners, flowise/templates/configmap.yaml, flowise/templates/flowise.yaml, flowise/values.yaml
>Flowise
> Drag & drop UI to build your customized LLM flow
=> [NEW][flowise][1.0.1] add app flowise

anythingllm/Chart.yaml, anythingllm/OlaresManifest.yaml
AnythingLLM
remove api timeout limit.
=> [UPDATE][anythingllm][1.0.2]remove api timeout limit

mtranserver/Chart.yaml, mtranserver/OlaresManifest.yaml, mtranserver/templates/clientproxy.yaml, mtranserver/templates/mtranserver.yaml
mtranserver
- update app versions
- add proxy
=> [UPDATE][mtranserver][1.0.2] update app version and proxy

redroid/.helmignore, redroid/Chart.yaml, redroid/OlaresManifest.yaml, redroid/i18n/en-US/OlaresManifest.yaml, redroid/i18n/zh-CN/OlaresManifest.yaml, redroid/owners, redroid/templates/redroid.yaml, redroid/values.yaml
=> [NEW][redroid][1.0.1] new app redroid

windows/Chart.yaml, windows/OlaresManifest.yaml
> windows
> fix: windows change tailscale acl
=> [UPDATE][windows][1.0.8]fix: windows change tailscale acl

wewerss/Chart.yaml, wewerss/OlaresManifest.yaml, wewerss/i18n/en-US/OlaresManifest.yaml, wewerss/i18n/zh-CN/OlaresManifest.yaml, wewerss/templates/mysql/deployment.yaml, wewerss/templates/secret.yaml, wewerss/templates/wewerss.yaml, wewerss/values.yaml
> WeWe Rss.
> update wewerss remove .suspend file.
=> [UPDATE][wewerss][1.0.2] update wewerss remove .suspend file

wewerss/Chart.yaml, wewerss/OlaresManifest.yaml, wewerss/i18n/en-US/OlaresManifest.yaml, wewerss/i18n/zh-CN/OlaresManifest.yaml
> WeWe Rss.
> upgrade description.
=> [UPDATE][wewerss][1.0.3] update wewerss upgrade description

steamheadless/Chart.yaml, steamheadless/OlaresManifest.yaml, steamheadless/owners
Steam Headless
update acls for OS version >= 1.11.6
=> [UPDATE][steamheadless][1.0.7]update acls

wewerss/Chart.yaml, wewerss/OlaresManifest.yaml, wewerss/templates/clientproxy.yaml, wewerss/templates/wewerss.yaml
> WeWe Rss
> remove SERVER_ORIGIN_URL
>add proxy
=> [UPDATE][wewerss][1.0.4]remove SERVER_ORIGIN_URL add proxy

seatable/Chart.yaml, seatable/OlaresManifest.yaml, seatable/templates/clientproxy.yaml
> seatable
> update proxy rule
=> [UPDATE][seatable][1.0.2] update proxy rule

coder/Chart.yaml, coder/OlaresManifest.yaml
=> [UPDATE][coder][1.0.2]add images

wewerss/Chart.yaml, wewerss/OlaresManifest.yaml, wewerss/templates/mysql/deployment.yaml
> WeWe Rss
> update mysql args
> update authLevel rule
=> [UPDATE][wewerss][1.0.5] update mysql args and authLevel

cloudreve/Chart.yaml, cloudreve/OlaresManifest.yaml
=> [UPDATE][cloudreve][1.0.2]add images

lobechat/Chart.yaml, lobechat/OlaresManifest.yaml, lobechat/owners, lobechat/templates/lobechat.yaml
=> [UPDATE][lobechat][0.0.3]upgrade to 1.79.4

migpttts/.helmignore, migpttts/Chart.yaml, migpttts/OlaresManifest.yaml, migpttts/i18n/en-US/OlaresManifest.yaml, migpttts/i18n/zh-CN/OlaresManifest.yaml, migpttts/owners, migpttts/templates/clientproxy.yaml, migpttts/templates/configmap.yaml, migpttts/templates/migpttts.yaml, migpttts/values.yaml
=> [NEW][migpttts][1.0.1]add app migpttts

excalidraw/Chart.yaml, excalidraw/OlaresManifest.yaml
=> [UPDATE][excalidraw][1.0.2]add img

redroid/Chart.yaml, redroid/OlaresManifest.yaml
=> [UPDATE][redroid][1.0.2]add img

md/Chart.yaml, md/OlaresManifest.yaml
WeChat Markdown Editor
add img
=> [UPDATE][md][1.0.2]add img

localai/Chart.yaml, localai/OlaresManifest.yaml, localai/templates/localai.yaml
=> [UPDATE][localai][1.0.2]add img

firecrawl/Chart.yaml, firecrawl/OlaresManifest.yaml, firecrawl/templates/api.yaml, firecrawl/templates/configmap.yaml, firecrawl/templates/playwright-service.yaml, firecrawl/templates/worker.yaml
> firecrawl
> update docker image
> update config
=> [UPDATE][firecrawl][1.0.2] update docker image and config

steamheadless/Chart.yaml, steamheadless/OlaresManifest.yaml, steamheadless/i18n/en-US/OlaresManifest.yaml, steamheadless/i18n/zh-CN/OlaresManifest.yaml
=> [UPDATE][steamheadless][1.0.9]fix title

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/i18n/en-US/OlaresManifest.yaml, comfyuishare/i18n/zh-CN/OlaresManifest.yaml, comfyuishare/owners, comfyuishare/templates/clientproxy.yaml, comfyuishare/templates/configmap.yaml, comfyuishare/templates/deployment.yaml
ComfyUI Shared
Add  ComfyUI and ComfyUI Launcher
Change to shared one-pack arch
=> [NEW][comfyuishare][1.2.2]Add ComfyUI with Launcher

seatable/Chart.yaml, seatable/OlaresManifest.yaml, seatable/templates/mariadb/deployment.yaml, seatable/templates/seatable.yaml
App Title
seatable
Description
update requiredCup 1
=> [UPDATE][seatable][1.0.4]update requiredCup 1

dify/Chart.yaml, dify/OlaresManifest.yaml
=> [UPDATE][dify][1.1.3]fix version

seatable/Chart.yaml, seatable/OlaresManifest.yaml
> Seatable
> remove seatable supportArch arm64
=> [UPDATE][seatable][1.0.5]remove seatable supportArch arm64

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/templates/clientproxy.yaml
> comfyuishare
> fix server host in client
=> [UPDATE][comfyuishare][1.2.4]fix server host in client

dify/Chart.yaml, dify/OlaresManifest.yaml, dify/templates/server/api/api-deployment.yaml, dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
> dify
> add health_check_interval for redis
=> [UPDATE][dify][1.1.4]add health check interval for redis

nextcloud/Chart.yaml, nextcloud/OlaresManifest.yaml, nextcloud/i18n/en-US/OlaresManifest.yaml, nextcloud/i18n/zh-CN/OlaresManifest.yaml, nextcloud/owners, nextcloud/templates/clientproxy.yaml, nextcloud/templates/configmap.yaml, nextcloud/templates/deployment.yaml, nextcloud/values.yaml
nextcloud
fix nextcloud bug for External Storage and Home Storage
=> [UPDATE][nextcloud][1.0.4]fix nextcloud bug for External Storage and Home Storage

seatable/Chart.yaml, seatable/OlaresManifest.yaml, seatable/templates/mariadb/deployment.yaml, seatable/templates/seatable.yaml
> Seatable.
> update cpu and memory, rollback
=> [UPDATE][seatable][1.0.6]update cpu and memory

seatable/Chart.yaml, seatable/OlaresManifest.yaml, seatable/templates/mariadb/deployment.yaml, seatable/templates/seatable.yaml
> Seatable
> fix bug:init tc-log error
=> [UPDATE][seatable][1.0.7]fix bug:init tc-log error

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/i18n/en-US/OlaresManifest.yaml
=> [UPDATE][comfyuishare][1.2.5]fix en title

immich/Chart.yaml, immich/OlaresManifest.yaml, immich/owners, immich/templates/machine-learning.yaml, immich/templates/server.yaml
immich
- update client
- update app version
=> [UPDATE][immich][1.0.3]update client and app versions

immich/Chart.yaml, immich/OlaresManifest.yaml, immich/i18n/en-US/OlaresManifest.yaml, immich/i18n/zh-CN/OlaresManifest.yaml, immich/templates/clientproxy.yaml
=> [UPDATE][immich][1.0.4]update app versions

firecrawl/Chart.yaml, firecrawl/OlaresManifest.yaml
=> [UPDATE][firecrawl][1.0.3]add img

hoppscotch/Chart.yaml, hoppscotch/OlaresManifest.yaml
=> [UPDATE][hoppscotch][1.0.2]add img

migpt/Chart.yaml, migpt/OlaresManifest.yaml
=> [UPDATE][migpt][1.0.2]add imgs

migpttts/Chart.yaml, migpttts/OlaresManifest.yaml
=> [UPDATE][migpttts][1.0.2]add imgs

dify/Chart.yaml, dify/OlaresManifest.yaml, dify/templates/server/nginx/nginx-deployment.yaml, dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
App Title
dify
Description
fix: dify image image pull policy
=> [UPDATE][dify][1.1.6]fix: dify image image pull policy

affine/Chart.yaml, affine/OlaresManifest.yaml, affine/templates/deployment.yaml, astral/Chart.yaml, astral/OlaresManifest.yaml, astral/templates/deployment.yaml, bazarr/Chart.yaml, bazarr/OlaresManifest.yaml, bazarr/templates/deployment.yaml, chaosmesh/Chart.yaml, chaosmesh/OlaresManifest.yaml, chaosmesh/templates/prometheus-deployment.yaml, duplicati/Chart.yaml, duplicati/OlaresManifest.yaml, duplicati/templates/deployment.yaml, geth/Chart.yaml, geth/OlaresManifest.yaml, geth/templates/website.yaml, mongodb/Chart.yaml, mongodb/OlaresManifest.yaml, mongodb/templates/deployment.yaml, navidrome/Chart.yaml, navidrome/OlaresManifest.yaml, navidrome/templates/deployment.yaml, prowlarr/Chart.yaml, prowlarr/OlaresManifest.yaml, prowlarr/templates/deployment.yaml, wordpress/Chart.yaml, wordpress/OlaresManifest.yaml, wordpress/templates/wordpress.yaml
> chaosmesh
> fix: change image latest pullpolicy to ifnotpresent
=> [UPDATE][chaosmesh]fix: change image latest pullpolicy to ifnotpresent

searxng/Chart.yaml, searxng/OlaresManifest.yaml, searxng/i18n/en-US/OlaresManifest.yaml, searxng/i18n/zh-CN/OlaresManifest.yaml, searxng/owners, searxng/templates/clientproxy.yaml, searxng/templates/deployment.yaml
searxng
update app versions
fix install bug
=> [UPDATE][searxng][1.0.4]update app version and fix bug

homeassistant/Chart.yaml, homeassistant/OlaresManifest.yaml, homeassistant/templates/deployment.yaml, searxng/Chart.yaml, searxng/OlaresManifest.yaml, searxng/i18n/en-US/OlaresManifest.yaml, searxng/i18n/zh-CN/OlaresManifest.yaml, searxng/owners, searxng/templates/clientproxy.yaml, searxng/templates/deployment.yaml
> homeassistant
> update app versions
=> [UPDATE][homeassistant][1.0.3] update app versions

onlyoffice/Chart.yaml, onlyoffice/OlaresManifest.yaml, onlyoffice/templates/deployment.yaml, onlyoffice/templates/proxy.yaml
onlyoffice
update deployment name
=> [UPDATE][onlyoffice][1.0.4]update deployment name

.idea/.gitignore, .idea/apps.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, affine/Chart.yaml, affine/OlaresManifest.yaml, affine/i18n/en-US/OlaresManifest.yaml, affine/i18n/zh-CN/OlaresManifest.yaml, affine/templates/deployment.yaml
> affine
> update app versions
=> [UPDATE][affine][1.0.3]update app versions

jaegerclient/Chart.yaml, jaegerclient/OlaresManifest.yaml, jaegerclient/i18n/en-US/OlaresManifest.yaml, jaegerclient/i18n/zh-CN/OlaresManifest.yaml, jaegerclient/templates/deployment.yaml
=> [UPDATE][jaegerclient][1.0.2]fix image policy

sdwebuishare/Chart.yaml, sdwebuishare/OlaresManifest.yaml, sdwebuishare/templates/server/deployment.yaml
=> [UPDATE][sdwebuishare][1.0.4]fix directory

sdwebuishare/Chart.yaml, sdwebuishare/OlaresManifest.yaml, sdwebuishare/templates/server/deployment.yaml
> sdwebuishare
> fix cacheforstartup path
=> [UPDATE][sdwebuishare][1.0.6]fix cacheforstartup path

astral/Chart.yaml, astral/OlaresManifest.yaml
=> [UPDATE][astral][1.0.2]change category

cosyvoice/templates/configmap.yaml, echomimicv2/templates/configmap.yaml, facefusion/templates/configmap.yaml, funclip/templates/configmap.yaml, whisperwebui/templates/configmap.yaml
Suspend cluster-server apps, use merged one-pack instead
fix CDN_HOST
=> Suspend cluster apps and fix CDN_HOST

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/i18n/en-US/OlaresManifest.yaml, comfyuishare/i18n/zh-CN/OlaresManifest.yaml, comfyuishare/templates/deployment.yaml
> comfyuishare
> Custom installation models and price differences, complete i18n solution
=> [UPDATE][comfyuishare][1.2.6]launcher up version

searxng/Chart.yaml, searxng/OlaresManifest.yaml, searxng/i18n/en-US/OlaresManifest.yaml, searxng/i18n/zh-CN/OlaresManifest.yaml, searxng/templates/deployment.yaml
searxng
update app versions
add resource limit
=> [UPDATE][searxng][1.0.5] upgrade app versions and resource limit

obsidian/Chart.yaml, obsidian/OlaresManifest.yaml, obsidian/templates/deployment.yaml
Obsidian LiveSync
update app versions
add resource limit
=> [UPDATE][obsidian][1.0.4]upgrade app versions and add resource limit

sdwebuishare/Chart.yaml, sdwebuishare/OlaresManifest.yaml, sdwebuishare/i18n/en-US/OlaresManifest.yaml, sdwebuishare/i18n/zh-CN/OlaresManifest.yaml, sdwebuishare/templates/server/deployment.yaml
=> [UPDATE][sdwebuishare][1.0.7]add gpu-inject

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/i18n/en-US/OlaresManifest.yaml, comfyuishare/i18n/zh-CN/OlaresManifest.yaml, comfyuishare/templates/deployment.yaml
> comfyuishare
> up version to v0.3.34
=> [UPDATE][comfyuishare][1.2.7]up version to v0.3.34

redroid/Chart.yaml, redroid/OlaresManifest.yaml, redroid/templates/redroid.yaml
redroid
remove default app yyb
=> [UPDATE][redroid][1.0.3]remove default app yyb

nocodb/Chart.yaml, nocodb/OlaresManifest.yaml, nocodb/i18n/en-US/OlaresManifest.yaml, nocodb/i18n/zh-CN/OlaresManifest.yaml, nocodb/templates/deployment.yaml
nocodb
fix title
add smtp config
update app versions
=> [UPDATE][nocodb][1.0.3] add smtp config update app versions

funclip/Chart.yaml, funclip/OlaresManifest.yaml, funclip/i18n/en-US/OlaresManifest.yaml, funclip/i18n/zh-CN/OlaresManifest.yaml, funclip/templates/clientproxy.yaml, funclip/templates/configmap.yaml, funclip/templates/funclip.yaml, funclip/values.yaml
funclip
update download models
update share mode
=> [UPDATE][funclip][1.0.5]upload download models and share mode

sdwebuiforgeshare/.helmignore, sdwebuiforgeshare/Chart.yaml, sdwebuiforgeshare/OlaresManifest.yaml, sdwebuiforgeshare/i18n/en-US/OlaresManifest.yaml, sdwebuiforgeshare/i18n/zh-CN/OlaresManifest.yaml, sdwebuiforgeshare/owners, sdwebuiforgeshare/templates/deployment.yaml, sdwebuiforgeshare/templates/entrances.yaml, sdwebuiforgeshare/values.yaml
> sdwebuiforgeshare
> new app SD-webUI-Forge-Share
=> [NEW][sdwebuiforgeshare][1.0.1]new app SD-webUI-Forge-Share

alist/Chart.yaml, alist/OlaresManifest.yaml, alist/templates/alist.yaml
=> [UPDATE][alist][1.0.4]replace image repo

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/i18n/en-US/OlaresManifest.yaml, comfyuishare/i18n/zh-CN/OlaresManifest.yaml, comfyuishare/templates/deployment.yaml
> comfyuishare
> up version 0.3.41
=> [UPDATE][comfyuishare][1.2.10]up version 0.3.41

dify/Chart.yaml, dify/OlaresManifest.yaml, dify/templates/server/api/api-deployment.yaml, dify/templates/server/plugin/plugin-daemon-deployment.yaml, dify/templates/server/web-deployment.yaml, dify/templates/server/worker/worker-deployment.yaml
> dify
> Dify up version 1.4.3
=> [UPDATE][dify][1.1.8]Dify up version 1.4.3

sdwebuiforgeshare/Chart.yaml, sdwebuiforgeshare/OlaresManifest.yaml, sdwebuiforgeshare/templates/deployment.yaml
> [UPDATE][sdwebuiforgeshare][1.0.2]
> fix lora plugin & update model path config
=> [UPDATE][sdwebuiforgeshare][1.0.2]fix lora plugin & update model path config

alist/Chart.yaml, alist/OlaresManifest.yaml, alist/templates/alist.yaml
alist
suspend app, use the merged one
=> [SUSPEND][alist][1.0.4]

pdfmathtranslate/.helmignore, pdfmathtranslate/Chart.yaml, pdfmathtranslate/OlaresManifest.yaml, pdfmathtranslate/i18n/en-US/OlaresManifest.yaml, pdfmathtranslate/i18n/zh-CN/OlaresManifest.yaml, pdfmathtranslate/owners, pdfmathtranslate/templates/configmap.yaml, pdfmathtranslate/templates/deployment.yaml
pdfmathtranslate
pdfmathtranslate
=> [NEW][pdfmathtranslate][1.0.1]app new app

hunyuan3dv21/.helmignore, hunyuan3dv21/Chart.yaml, hunyuan3dv21/OlaresManifest.yaml, hunyuan3dv21/i18n/en-US/OlaresManifest.yaml, hunyuan3dv21/i18n/zh-CN/OlaresManifest.yaml, hunyuan3dv21/owners, hunyuan3dv21/templates/clientproxy.yaml, hunyuan3dv21/templates/configmap.yaml, hunyuan3dv21/templates/deployment.yaml, hunyuan3dv21/values.yaml
=> [NEW][hunyuan3dv21][1.0.1]add new app hunyuan3dv21

chaosmesh/Chart.yaml, chaosmesh/OlaresManifest.yaml, chaosmesh/values.yaml
> chaosmesh
> fix: change image registry and repo
=> [UPDATE][chaosmesh][0.0.4]fix: change image registry and repo

ollama/Chart.yaml, ollama/OlaresManifest.yaml, ollama/i18n/en-US/OlaresManifest.yaml, ollama/i18n/zh-CN/OlaresManifest.yaml, ollama/templates/deployment.yaml
=> [UPDATE][ollama][1.1.1]Upgraded version 0.9.4

dify/Chart.yaml, dify/OlaresManifest.yaml, dify/templates/server/redis/redis-deployment.yaml
> dify
> Modify redis permissions
=> [UPDATE][dify][1.1.9]Modify redis permissions

pdfmathtranslate/Chart.yaml, pdfmathtranslate/OlaresManifest.yaml, pdfmathtranslate/templates/deployment.yaml
pdfmathtranslate
> upgrade app versions
=> [UPDATE][pdfmathtranslate][1.0.2]upgrade app versions

deerflow/Chart.yaml, deerflow/OlaresManifest.yaml, deerflow/i18n/en-US/OlaresManifest.yaml, deerflow/i18n/zh-CN/OlaresManifest.yaml, deerflow/templates/configmap.yaml, deerflow/templates/deployment.yaml, deerflow/templates/frontend.yaml
> deerflow
> upgrade app versions
> update config and .env mount
=> [UPDATE][deerflow][1.0.2]upgrade app versions

cosyvoice/Chart.yaml, cosyvoice/OlaresManifest.yaml, cosyvoice/templates/clientproxy.yaml, cosyvoice/templates/cosyvoice.yaml, cosyvoice/values.yaml
cosyvoice
> upgrade app versions
> update down models
> update share mode
=> [UPDATE][cosyvoice][1.0.6]upgrade app versions and update down models

cloudreve/Chart.yaml, cloudreve/OlaresManifest.yaml, cloudreve/templates/cloudreve.yaml, cloudreve/templates/configmap.yaml
cloudreve
> upgrade app versions 4.2
=> [UPDATE][cloudreve][1.0.3]upgrade app versions 4.2

cmproxy/Chart.yaml, cmproxy/OlaresManifest.yaml, cmproxy/i18n/en-US/OlaresManifest.yaml, cmproxy/i18n/zh-CN/OlaresManifest.yaml, cmproxy/templates/proxy.yaml
cmproxy
> upgrade app versions 2.24.9
=> [UPDATE][cmproxy][1.0.4]upgrade app versions 2.24.9

directus/Chart.yaml, directus/OlaresManifest.yaml, directus/i18n/en-US/OlaresManifest.yaml, directus/i18n/zh-CN/OlaresManifest.yaml, directus/templates/directus.yaml, directus/templates/redis/deployment.yaml
directus
> upgrade app versions 11.9.2
=> [UPDATE][directus][1.0.5]upgrade app versions 11.9.2

acestepv2/Chart.yaml, acestepv2/OlaresManifest.yaml
ace-step
add promoteImage and fix icon
=> [UPDATE][acestepv2][1.0.2]add promoteImage and fix icon

documenso/Chart.yaml, documenso/OlaresManifest.yaml, documenso/templates/documenso.yaml
documenso
upgrade app versions 1.12.1
=> [UPDATE][documenso][1.0.2]upgrade app versions 1.12.1

acestep/Chart.yaml, acestep/OlaresManifest.yaml
=> [UPDATE][acestep][1.0.7]update

halo/Chart.yaml, halo/OlaresManifest.yaml, halo/i18n/en-US/OlaresManifest.yaml, halo/i18n/zh-CN/OlaresManifest.yaml, halo/templates/deployment.yaml
halo
> upgrade app version 2.21.3
=> [UPDATE][halo][1.1.2]upgrade app version 2.21.3

hoppscotch/Chart.yaml, hoppscotch/OlaresManifest.yaml, hoppscotch/templates/hoppscotch.yaml
hoppscotch
> upgrade app version 2025.6.0
=> [UPDATE][hoppscotch][1.0.3]upgrade app version 2025.6.0

odoo/Chart.yaml, odoo/OlaresManifest.yaml, odoo/templates/odoo.yaml
> odoo
> upgrade app version 18.0-20250618
=> [UPDATE][odoo][1.0.2]upgrade app version 18.0-20250618

jaaz/.helmignore, jaaz/Chart.yaml, jaaz/OlaresManifest.yaml, jaaz/i18n/en-US/OlaresManifest.yaml, jaaz/i18n/zh-CN/OlaresManifest.yaml, jaaz/owners, jaaz/templates/configmap.yaml, jaaz/templates/deployment.yaml, jaaz/values.yaml
=> [NEW][jaaz][1.0.2]add new app jaaz

pdfmathtranslate/Chart.yaml, pdfmathtranslate/OlaresManifest.yaml, pdfmathtranslate/templates/deployment.yaml
pdfmathtranslate
> upgrade app version 1.9.11
=> [UPDATE][pdfmathtranslate][1.0.4]upgrade app version 1.9.11

acestepv2/Chart.yaml, acestepv2/OlaresManifest.yaml
=> [UPDATE][acestepv2][1.0.4]fix clusterScoped config

cosyvoice/Chart.yaml, cosyvoice/OlaresManifest.yaml
=> [UPDATE][cosyvoice][1.0.10]fix clusterScoped config 

onlyoffice/Chart.yaml, onlyoffice/OlaresManifest.yaml
=>  [UPDATE][onlyoffice][1.0.6]fix clusterScoped config

sdwebuiforgeshare/Chart.yaml, sdwebuiforgeshare/OlaresManifest.yaml
=> [UPDATE][sdwebuiforgeshare][1.0.4]fix clusterScoped config

sdwebuishare/Chart.yaml, sdwebuishare/OlaresManifest.yaml
=> [UPDATE][sdwebuishare][1.0.10]fix clusterScoped config

whisperwebui/Chart.yaml, whisperwebui/OlaresManifest.yaml
=>  [UPDATE][whisperwebui][1.0.7]fix clusterScoped config

stablefast3dshare/Chart.yaml, stablefast3dshare/OlaresManifest.yaml
=> [UPDATE][stablefast3dshare][1.0.4]fix clusterScoped config

chaosmesh/Chart.yaml, chaosmesh/OlaresManifest.yaml, chaosmesh/values.yaml
> chaosmesh
> fix: change pause image
=> [UPDATE][chaosmesh][0.0.6]fix: change pause image 

openedaispeech/Chart.yaml, openedaispeech/OlaresManifest.yaml
=> [UPDATE][openedaispeech][1.0.4]add onlyAdmin

chaosmesh/Chart.yaml, chaosmesh/OlaresManifest.yaml
> Chaosmesh
> suspend app, some image repo was disappear
=> [SUSPEND][chaosmesh][0.0.7]

whisperwebui/Chart.yaml, whisperwebui/OlaresManifest.yaml, whisperwebui/templates/clientproxy.yaml, whisperwebui/templates/deployment.yaml, whisperwebui/values.yaml
whisperwebui
> upgrade app version 1.0.5
> update download
=> [UPDATE][whisperwebui][1.0.8]upgrade app version 1.0.5

sdwebuishare/Chart.yaml, sdwebuishare/OlaresManifest.yaml
=> [UPDATE][sdwebuishare][1.0.11]fix syntax

hunyuan3dv21/Chart.yaml, hunyuan3dv21/OlaresManifest.yaml
=> [UPDATE][hunyuan3dv21][1.0.4]fix syntax

whisperwebui/Chart.yaml, whisperwebui/OlaresManifest.yaml
=> [UPDATE][whisperwebui][1.0.9]fix syntax

stablefast3dshare/Chart.yaml, stablefast3dshare/OlaresManifest.yaml, stablefast3dshare/templates/client/clientproxy.yaml
=> [UPDATE][stablefast3dshare][1.0.5]fix syntax

nocodb/Chart.yaml, nocodb/OlaresManifest.yaml, nocodb/i18n/en-US/OlaresManifest.yaml, nocodb/i18n/zh-CN/OlaresManifest.yaml, nocodb/templates/deployment.yaml
nocodb
upgrade app versions 0.263.8
update apiTimeout 0
add env NC_ATTACHMENT_FIELD_SIZE
=> [UPDATE][nocodb][1.0.5]upgrade app version 0.263.8

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/templates/deployment.yaml
=> [UPDATE][comfyuishare][1.2.16]fix upgrade

dify/Chart.yaml, dify/OlaresManifest.yaml
=> [UPDATE][dify][1.1.13]fix invalid dependencies

comfyuishare/Chart.yaml, comfyuishare/OlaresManifest.yaml, comfyuishare/i18n/en-US/OlaresManifest.yaml, comfyuishare/i18n/zh-CN/OlaresManifest.yaml, comfyuishare/templates/deployment.yaml
> comfyuishare
> up version to 0.3.51
=> [UPDATE][comfyuishare][1.2.17]up version to 0.3.51

mindmap/Chart.yaml, mindmap/OlaresManifest.yaml
=> [UPDATE][mindmap][1.0.7]fix supportArch

md/Chart.yaml, md/OlaresManifest.yaml, md/templates/md.yaml
WeChat Markdown Editor
upgrade version 2.0.4
=> [UPDATE][md][1.0.4]upgrade version 2.0.4

jaaz/Chart.yaml, jaaz/OlaresManifest.yaml, jaaz/templates/deployment.yaml
jaaz
- upgrade version 1.0.7
- add arm64 arch
=> [UPDATE][jaaz][1.0.4]upgrade version 1.0.7 and add arm64 arch

astrbot/Chart.yaml, astrbot/OlaresManifest.yaml, astrbot/templates/deployment.yaml
astrbot
- upgrade version 3.5.26
- add supportArch arm64
=> [UPDATE][astrbot][1.0.1]upgrade version 3.5.26 add supportArch arm64

cmproxy/Chart.yaml, cmproxy/OlaresManifest.yaml, cmproxy/i18n/en-US/OlaresManifest.yaml, cmproxy/i18n/zh-CN/OlaresManifest.yaml, cmproxy/templates/proxy.yaml
cmproxy
- upgrade app versions 2.25.3
- add supportArch arm64
=> [UPDATE][cmproxy][1.0.6]upgrade version 2.25.3 add supportArch arm64

hasura/Chart.yaml, hasura/OlaresManifest.yaml, hasura/i18n/en-US/OlaresManifest.yaml, hasura/i18n/zh-CN/OlaresManifest.yaml, hasura/templates/hasura.yaml
hasura
- upgrade version 2.48.4
- add supportArch arm64
=> [UPDATE][hasura][1.0.4]upgrade version 2.48.4 add supportArch arm64

photoprism/Chart.yaml, photoprism/OlaresManifest.yaml, photoprism/templates/deployment.yaml
photoprism
> update openMethod window
=> [UPDATE][photoprism][1.0.5]update openMethod window

perplexica/Chart.yaml, perplexica/OlaresManifest.yaml, perplexica/templates/1-10-2/deployment.yaml
=> [UPDATE][perplexica][1.1.3]fix init bug

jellyfin/Chart.yaml, jellyfin/OlaresManifest.yaml, jellyfin/templates/deployment.yaml
=> [UPDATE][jellyfin][1.0.6]chang to rbac provider

sickchill/Chart.yaml, sickchill/OlaresManifest.yaml, sickchill/templates/deployment.yaml
=> [UPDATE][sickchill][1.0.5]chang to rbac provider

secondme/Chart.yaml, secondme/OlaresManifest.yaml
=> [UPDATE][secondme][1.0.4]chang to rbac provider

searxng/Chart.yaml, searxng/OlaresManifest.yaml, searxng/templates/deployment.yaml
=> [UPDATE][searxng][1.0.10]chang to rbac provider

readarr/Chart.yaml, readarr/OlaresManifest.yaml, readarr/templates/deployment.yaml
=> [UPDATE][readarr][1.0.3]chang to rbac provider

ragflow/Chart.yaml, ragflow/OlaresManifest.yaml
=> [UPDATE][ragflow][1.0.10]chang to rbac provider

radarr/Chart.yaml, radarr/OlaresManifest.yaml, radarr/templates/deployment.yaml
=> [UPDATE][radarr][1.0.3]chang to rbac provider

qbittorrent/Chart.yaml, qbittorrent/OlaresManifest.yaml, qbittorrent/templates/deployment.yaml
=> [UPDATE][qbittorrent][1.0.7]chang to rbac provider

prowlarr/Chart.yaml, prowlarr/OlaresManifest.yaml, prowlarr/templates/deployment.yaml
=> [UPDATE][prowlarr][1.0.4]chang to rbac provider

nzbget/Chart.yaml, nzbget/OlaresManifest.yaml, nzbget/templates/deployment.yaml
=> [UPDATE][nzbget][1.0.3]chang to rbac provider

anythingllm/Chart.yaml, anythingllm/OlaresManifest.yaml, anythingllm/templates/anythingllm.yaml
=> [UPDATE][anythingllm][1.0.4]chang to rbac provider

deerflow/Chart.yaml, deerflow/OlaresManifest.yaml
=> [UPDATE][deerflow][1.0.5]chang to rbac provider

migpt/Chart.yaml, migpt/OlaresManifest.yaml
=> [UPDATE][migpt][1.0.4]chang to rbac provider

lobechat/Chart.yaml, lobechat/OlaresManifest.yaml
=> [UPDATE][lobechat][1.0.1]chang to rbac provider

jaegerclient/Chart.yaml, jaegerclient/OlaresManifest.yaml, jaegerclient/templates/deployment.yaml
=> [UPDATE][jaegerclient][1.0.4]chang to rbac provider
